import { describe, expect, it } from "vitest";
import { parseYouTubeTranscriptMarkdown } from "../youtube-transcript";

describe("YouTube transcript responses", () => {
  it("turns the provider document into clean timed transcript text", () => {
    expect(parseYouTubeTranscriptMarkdown(`# Transcript: 日本語のレッスン

Source video: https://www.youtube.com/watch?v=abcdefghijk
Language: ja · Duration: 1:20 · Words: 12
Other available languages: en (en)

[0:00] こんにちは。
今日は天気です。

[1:02.50] また明日。

---
Generated by https://youtube-transcript.ai`)).toEqual({
      title: "日本語のレッスン",
      language: "ja",
      transcript: "[0:00]こんにちは。 今日は天気です。\n[1:02.50]また明日。",
      cueCount: 2,
    });
  });

  it("rejects documents without timed caption paragraphs", () => {
    expect(() => parseYouTubeTranscriptMarkdown("# Transcript: unavailable\n\nNo captions found."))
      .toThrow("No timed captions were found");
  });
});
