import type { JlptQuestion } from "../types";
import { N1_GENERATED_QUESTIONS } from "./generated/n1.generated";

const options = (...labels: string[]) =>
  labels.map((label, index) => ({ id: String(index + 1), label }));

const N1_AUTHORED_QUESTIONS: readonly JlptQuestion[] = [
  {
    id: "n1-kanji-zeijaku",
    level: "N1",
    skill: "kanji",
    officialType: "kanji-reading",
    shortQuiz: true,
    instruction: "Choose the correct reading for the underlined word.",
    stem: "災害時にも止まらないよう、脆弱な部分を改修する必要がある。",
    focus: "脆弱",
    options: options("きじゃく", "ぜいじゃく", "ぜいにゃく", "もろじゃく"),
    correctOptionId: "2",
    explanation: "脆弱 is read ぜいじゃく and means fragile or vulnerable.",
    relatedKanji: [
      "災",
      "害",
      "時",
      "止",
      "脆",
      "弱",
      "部",
      "分",
      "改",
      "修",
      "必",
      "要",
    ],
  },
  {
    id: "n1-kanji-toushuu",
    level: "N1",
    skill: "kanji",
    officialType: "kanji-reading",
    instruction: "Choose the correct reading for the underlined word.",
    stem: "前任者の方針をそのまま踏襲するのではなく、現状に合わせて見直した。",
    focus: "踏襲",
    options: options("とうしゅう", "ふしゅう", "とうじゅう", "ふとう"),
    correctOptionId: "1",
    explanation:
      "踏襲 is read とうしゅう and means following or carrying on an established policy or method.",
    relatedKanji: [
      "前",
      "任",
      "者",
      "方",
      "針",
      "踏",
      "襲",
      "現",
      "状",
      "合",
      "見",
      "直",
    ],
  },
  {
    id: "n1-context-shisa",
    level: "N1",
    skill: "vocabulary",
    officialType: "context-expression",
    shortQuiz: true,
    instruction: "Choose the word that best completes the sentence.",
    stem: "今回の調査結果は、制度の周知だけでは利用が広がらない可能性を＿＿している。",
    options: options("示唆", "指図", "告白", "予告"),
    correctOptionId: "1",
    explanation:
      "示唆する means to suggest or imply a conclusion indirectly, which fits what research findings indicate.",
    relatedKanji: [
      "今",
      "回",
      "調",
      "査",
      "結",
      "果",
      "制",
      "度",
      "周",
      "知",
      "利",
      "用",
      "広",
      "可",
      "能",
      "性",
      "示",
      "唆",
    ],
  },
  {
    id: "n1-context-hitohada",
    level: "N1",
    skill: "vocabulary",
    officialType: "context-expression",
    instruction: "Choose the word that best completes the sentence.",
    stem: "地域の文化を守ることは、＿＿次の世代が自分たちの歴史を理解することにもつながる。",
    options: options("ひいては", "かたわら", "もっぱら", "さも"),
    correctOptionId: "1",
    explanation:
      "ひいては extends the consequence to a broader result: preserving culture, and ultimately helping the next generation understand its history.",
    relatedKanji: [
      "地",
      "域",
      "文",
      "化",
      "守",
      "次",
      "世",
      "代",
      "自",
      "分",
      "歴",
      "史",
      "理",
      "解",
    ],
  },
  {
    id: "n1-paraphrase-nashikuzushi",
    level: "N1",
    skill: "vocabulary",
    officialType: "paraphrase",
    shortQuiz: true,
    instruction: "Choose the expression with nearly the same meaning.",
    stem: "明確な合意がないまま、計画はなし崩しに変更されていった。",
    focus: "なし崩しに",
    options: options(
      "段階的だが既成事実を重ねる形で",
      "全員の合意を一度に得て",
      "当初の内容を厳密に守って",
      "一時的に中断したあとで",
    ),
    correctOptionId: "1",
    explanation:
      "なし崩しに describes something being changed little by little without a clear formal decision, often through accumulating faits accomplis.",
    relatedKanji: [
      "明",
      "確",
      "合",
      "意",
      "計",
      "画",
      "変",
      "更",
      "段",
      "階",
      "的",
      "既",
      "成",
      "事",
      "実",
      "重",
      "形",
    ],
  },
  {
    id: "n1-usage-kanka",
    level: "N1",
    skill: "vocabulary",
    officialType: "usage",
    instruction:
      "Choose the sentence in which the underlined word is used correctly.",
    stem: "看過",
    options: options(
      "小さな記録のずれでも、安全に関わるなら看過できない。",
      "景色が美しかったので、展望台から一時間看過した。",
      "申請書を看過してから、窓口に提出してください。",
      "議論が長引いたため、結論を来週まで看過した。",
    ),
    correctOptionId: "1",
    explanation:
      "看過 means overlooking or letting a problem pass without action, normally in 看過できない. The other sentences require 見渡す, 確認する, or 延期する.",
    relatedKanji: ["看", "過", "小", "記", "録", "安", "全", "関"],
  },
  {
    id: "n1-grammar-kinjienai",
    level: "N1",
    skill: "grammar",
    officialType: "grammar-form",
    shortQuiz: true,
    instruction: "Choose the form that best completes the sentence.",
    stem: "被災地から届いた報告を読み、支援の遅れに憤りを＿＿。",
    options: options(
      "禁じ得なかった",
      "余儀なくされた",
      "ものとした",
      "ものともせずにいた",
    ),
    correctOptionId: "1",
    explanation:
      "感情を禁じ得ない means one cannot suppress an emotion. 憤り is the emotion felt after reading the report.",
    relatedKanji: [
      "被",
      "災",
      "地",
      "届",
      "報",
      "告",
      "読",
      "支",
      "援",
      "遅",
      "憤",
      "禁",
      "得",
    ],
  },
  {
    id: "n1-grammar-tomonaruto",
    level: "N1",
    skill: "grammar",
    officialType: "grammar-form",
    instruction: "Choose the form that best completes the sentence.",
    stem: "組織を代表する立場＿＿、個人の好みだけで判断するわけにはいかない。",
    options: options("ともなると", "とあっては", "ならでは", "にもまして"),
    correctOptionId: "1",
    explanation:
      "Xともなると means when one reaches a significant position or situation such as representing an organization.",
    relatedKanji: [
      "組",
      "織",
      "代",
      "表",
      "立",
      "場",
      "個",
      "人",
      "好",
      "判",
      "断",
    ],
  },
  {
    id: "n1-composition-evidence",
    level: "N1",
    skill: "grammar",
    officialType: "sentence-composition",
    shortQuiz: true,
    instruction:
      "Put the four parts in the correct order. Which part goes in ★?",
    stem: "この仮説は　＿＿　＿＿　★　＿＿　とは言い難い。",
    options: options(
      "十分な証拠に",
      "現段階では",
      "裏付けられている",
      "よって",
    ),
    correctOptionId: "4",
    sentenceComposition: {
      canonicalOrderOptionIds: ["2", "1", "4", "3"],
      starredPosition: 2,
    },
    explanation:
      "The natural order is 現段階では 十分な証拠に よって 裏付けられているとは言い難い. よって occupies the starred third position.",
    relatedKanji: [
      "仮",
      "説",
      "現",
      "段",
      "階",
      "十",
      "分",
      "証",
      "拠",
      "裏",
      "付",
      "言",
      "難",
    ],
  },
  {
    id: "n1-text-grammar-innovation",
    level: "N1",
    skill: "grammar",
    officialType: "text-grammar",
    instruction:
      "Read the passage and choose the expression that best fits the blank.",
    stem: "（　）に入るものとして、最もよいものを一つ選んでください。",
    passage: {
      body: "新しい技術は、導入しただけで組織を変えるわけではない。従来の手続きに無理に当てはめれば、かえって確認作業が増え、意思決定が遅くなることさえある。＿＿、技術の導入と同時に、仕事の目的や役割分担そのものを見直す必要がある。道具の新しさではなく、仕事の設計を問い直せるかどうかが成果を左右するのである。",
    },
    options: options(
      "それにもかかわらず",
      "したがって",
      "もっとも",
      "ところが",
    ),
    correctOptionId: "2",
    explanation:
      "したがって introduces the conclusion derived from the preceding problem: the workflow and roles must also be reconsidered.",
    relatedKanji: [
      "新",
      "技",
      "術",
      "導",
      "入",
      "組",
      "織",
      "変",
      "従",
      "来",
      "手",
      "続",
      "無",
      "理",
      "当",
      "作",
      "業",
      "複",
      "雑",
      "同",
      "時",
      "仕",
      "事",
      "目",
      "的",
      "役",
      "割",
      "分",
      "担",
      "見",
      "直",
      "必",
      "要",
    ],
  },
  {
    id: "n1-reading-measure",
    level: "N1",
    skill: "reading",
    officialType: "reading-short",
    shortQuiz: true,
    instruction: "Read the passage and choose the correct answer.",
    stem: "筆者が指標について注意すべきだと述べていることは何か。",
    passage: {
      body: "何かを改善しようとするとき、成果を数値で測ることは有効だ。ただし、測りやすいものが、本当に重要なものとは限らない。問い合わせへの対応時間だけを短くしようとすれば、相手の問題を十分に理解しないまま会話を終えることさえ起こりうる。指標は現実を映す窓ではあるが、窓から見えない部分が消えるわけではない。",
    },
    options: options(
      "数値で測れる成果は重要ではない。",
      "対応時間は長いほどよい。",
      "指標だけを目標にすると、測れない重要な点を損なうことがある。",
      "問い合わせへの対応は数値化できない。",
    ),
    correctOptionId: "3",
    explanation:
      "The writer warns that optimizing a measurable proxy can damage important aspects that the metric does not capture.",
    relatedKanji: [
      "何",
      "改",
      "善",
      "成",
      "果",
      "数",
      "値",
      "測",
      "有",
      "効",
      "重",
      "要",
      "限",
      "問",
      "合",
      "対",
      "応",
      "時",
      "間",
      "短",
      "相",
      "手",
      "問",
      "題",
      "十",
      "分",
      "理",
      "解",
      "会",
      "話",
      "終",
      "起",
      "指",
      "標",
      "現",
      "実",
      "映",
      "窓",
      "見",
      "部",
      "分",
      "消",
    ],
  },
  {
    id: "n1-reading-map",
    level: "N1",
    skill: "reading",
    officialType: "reading-mid",
    shortQuiz: true,
    instruction: "Read the passage and choose the writer's view.",
    stem: "筆者は古い地図を保存する意義をどのように捉えているか。",
    passage: {
      body: "古い地図を保存する理由として、失われた町並みを後世に伝えることが挙げられる。しかし地図の価値は、過去を懐かしむ材料にとどまらない。どの道が広げられ、どの川が地下に移されたかを現在の地図と比べれば、都市が何を優先してきたかが見えてくる。\nもちろん、地図は当時の現実をそのまま写したものではない。作成者の目的によって、省かれた情報や強調された場所がある。だからこそ、地図を唯一の事実として扱うのではなく、行政文書や住民の記録と突き合わせる必要がある。異なる資料のずれは欠点ではなく、誰が町をどう見ていたかを考える手がかりになる。保存とは、過去の姿を固定することではない。現在とは異なる複数の見方を、将来の検討に開いておくことなのである。",
    },
    options: options(
      "古い地図は正確でないため、行政文書より価値が低い。",
      "古い地図は昔の町並みを懐かしむためだけに保存すべきだ。",
      "複数の資料と比較することで、都市の選択や異なる視点を検討できる。",
      "地図の情報のずれは、保存前に一つの事実へ修正すべきだ。",
    ),
    correctOptionId: "3",
    explanation:
      "The writer values maps as one perspective that, compared with other records, reveals urban priorities and differing views.",
    relatedKanji: [
      "古",
      "地",
      "図",
      "保",
      "存",
      "理",
      "由",
      "失",
      "町",
      "並",
      "後",
      "世",
      "伝",
      "価",
      "値",
      "過",
      "去",
      "懐",
      "材",
      "道",
      "広",
      "川",
      "下",
      "移",
      "現",
      "在",
      "比",
      "都",
      "市",
      "何",
      "優",
      "先",
      "当",
      "時",
      "実",
      "写",
      "作",
      "成",
      "者",
      "目",
      "的",
      "省",
      "情",
      "報",
      "強",
      "調",
      "場",
      "所",
      "唯",
      "一",
      "事",
      "実",
      "扱",
      "行",
      "政",
      "文",
      "書",
      "住",
      "民",
      "記",
      "録",
      "突",
      "合",
      "必",
      "要",
      "異",
      "資",
      "料",
      "欠",
      "点",
      "誰",
      "考",
      "手",
      "固",
      "複",
      "数",
      "見",
      "方",
      "将",
      "来",
      "検",
      "討",
      "開",
    ],
  },
  {
    id: "n1-reading-friction",
    level: "N1",
    skill: "reading",
    officialType: "reading-long",
    instruction:
      "Read the passage and choose the best summary of the argument.",
    stem: "この文章で筆者が主張していることは何か。",
    passage: {
      body: "便利な道具は、目的に至るまでの手間を減らす。検索すれば情報が見つかり、ボタンを押せば商品が届く。手間が減ること自体を惜しむ必要はない。問題は、あらゆる手間を同じように無駄と見なすときに生じる。\n例えば、文章を書く前に資料を並べ替える作業は、完成した文章には直接現れない。効率だけを見れば、自動化したくなるだろう。しかし、並べ替える途中で、似ていると思っていた二つの例が実は異なることに気づいたり、重要でないと考えていた記録が別の資料と結びついたりする。ここでの手間は、すでに決まった答えへ向かう障害ではなく、何を問うべきかを見つける過程でもある。\nもちろん、すべての不便に価値があるわけではない。単純な転記や、同じ情報の繰り返し入力は、考える機会をほとんど生まない。区別すべきなのは、手間があるかないかではなく、その手間が判断を要求するかどうかである。\n技術を導入するとき、『何が速くなるか』だけを尋ねると、判断を伴う過程まで消してしまう恐れがある。むしろ、機械に任せる部分と、人が立ち止まる部分を意識して設計する必要がある。便利さとは、摩擦をゼロにすることではなく、不要な摩擦を減らし、必要な摩擦を残すことなのだ。",
    },
    options: options(
      "効率化は思考を妨げるため、便利な道具を使うべきではない。",
      "すべての手間には価値があるので、自動化を避けるべきだ。",
      "手間が判断や発見を生むかを見極め、不要なものだけを自動化すべきだ。",
      "文章を書く前の資料整理だけは、機械に任せてはならない。",
    ),
    correctOptionId: "3",
    explanation:
      "The conclusion distinguishes empty repetition from productive friction and argues that automation should preserve processes involving judgment and discovery.",
    relatedKanji: [
      "便",
      "利",
      "道",
      "具",
      "目",
      "的",
      "至",
      "手",
      "間",
      "減",
      "検",
      "索",
      "情",
      "報",
      "見",
      "商",
      "品",
      "届",
      "自",
      "体",
      "惜",
      "必",
      "要",
      "問",
      "題",
      "無",
      "駄",
      "生",
      "例",
      "文",
      "章",
      "書",
      "前",
      "資",
      "料",
      "並",
      "替",
      "作",
      "業",
      "完",
      "成",
      "直",
      "接",
      "現",
      "効",
      "率",
      "自",
      "動",
      "化",
      "途",
      "中",
      "似",
      "二",
      "実",
      "異",
      "気",
      "重",
      "要",
      "考",
      "記",
      "録",
      "別",
      "結",
      "決",
      "答",
      "向",
      "障",
      "害",
      "何",
      "過",
      "程",
      "不",
      "価",
      "値",
      "単",
      "純",
      "転",
      "記",
      "同",
      "繰",
      "返",
      "入",
      "力",
      "機",
      "会",
      "区",
      "判",
      "断",
      "要",
      "求",
      "技",
      "術",
      "導",
      "何",
      "速",
      "尋",
      "伴",
      "消",
      "恐",
      "機",
      "械",
      "任",
      "部",
      "分",
      "人",
      "立",
      "止",
      "意",
      "識",
      "設",
      "計",
      "摩",
      "擦",
      "残",
    ],
  },
  {
    id: "n1-reading-integrated-ai",
    level: "N1",
    skill: "reading",
    officialType: "reading-integrated",
    instruction: "Read both opinions and choose the most accurate comparison.",
    stem: "AとBの意見はどのように異なるか。",
    passage: {
      title: "自動判定システムの説明",
      body: "【A】自動判定の根拠をすべて公開すれば、不正に仕組みを利用する者が現れる。利用者には、判断に使う主な項目と異議申立ての方法を示せば十分だ。完全な公開より、制度が悪用されないことを優先すべきである。\n\n【B】仕組みの悪用を防ぐ必要はあるが、『主な項目』だけでは、なぜ自分が不利益を受けたのか検証できない。個々の判断について、どの情報がどの程度影響したかを本人が確認でき、誤った情報を訂正できる設計が必要だ。",
    },
    options: options(
      "Aは自動判定そのものに反対し、Bは無条件に賛成している。",
      "Aは悪用防止のため説明を限定すべきだとし、Bは個別判断を検証・訂正できる説明が必要だとしている。",
      "AもBも、判定根拠を一般にすべて公開すべきだとしている。",
      "Aは異議申立てを不要とし、Bは人による判定を廃止すべきだとしている。",
    ),
    correctOptionId: "2",
    explanation:
      "A prioritizes limited disclosure to prevent gaming, whereas B requires person-specific traceability and correction without demanding universal publication.",
    relatedKanji: [
      "自",
      "動",
      "判",
      "定",
      "説",
      "明",
      "根",
      "拠",
      "公",
      "開",
      "不",
      "正",
      "仕",
      "組",
      "利",
      "用",
      "者",
      "現",
      "判",
      "断",
      "使",
      "主",
      "項",
      "目",
      "異",
      "議",
      "申",
      "立",
      "方",
      "法",
      "示",
      "十",
      "分",
      "完",
      "全",
      "制",
      "度",
      "悪",
      "用",
      "優",
      "先",
      "防",
      "必",
      "要",
      "自",
      "分",
      "利",
      "益",
      "受",
      "検",
      "証",
      "個",
      "情",
      "報",
      "程",
      "度",
      "影",
      "響",
      "本",
      "人",
      "確",
      "認",
      "誤",
      "訂",
      "正",
      "設",
      "計",
    ],
  },
  {
    id: "n1-reading-thematic-uncertainty",
    level: "N1",
    skill: "reading",
    officialType: "reading-thematic",
    instruction: "Read the passage and choose the writer's central claim.",
    stem: "筆者が不確実な情報の伝え方について最も重要だと考えていることは何か。",
    passage: {
      body: "将来の予測を伝える際、断定を避けると『自信がない』と受け取られることがある。そのため、複雑な条件を省き、結論だけを明快に示したくなる。しかし、不確実性を隠した説明は、短期的には理解されやすくても、予測が外れたときに信頼を大きく損なう。\nでは、考えられる可能性をすべて並べればよいのか。そうとも限らない。細かな例外を羅列すれば、受け手は何を基準に行動すべきか分からなくなる。不確実性を誠実に伝えることと、判断を相手に丸投げすることは同じではない。\n必要なのは、何が比較的確かで、どの部分が条件に左右され、状況が変わればどの指標を見直すのかを区別して示すことだ。例えば『必ず起こる』か『起こらない』かの二択ではなく、現時点で最も可能性が高い見通しと、それを変えうる要因を示す。そうすれば、受け手は結論だけを信じるのではなく、変化に応じて判断を更新できる。\n説明の明快さは、迷いを見せないことではない。どこまで分かっていて、どこから先は分からないのか、その境界を共有することにある。",
    },
    options: options(
      "不確実性に触れず、最も可能性の高い結論だけを断定すること",
      "例外を漏れなく列挙し、最終判断をすべて受け手に任せること",
      "確かな点・条件次第の点・見直しの手がかりを分け、判断を更新できるようにすること",
      "予測が外れた場合に備え、具体的な見通しを一切示さないこと",
    ),
    correctOptionId: "3",
    explanation:
      "The writer defines clarity as sharing the boundary of knowledge and the factors that should trigger updated judgment.",
    relatedKanji: [
      "筆",
      "者",
      "不",
      "確",
      "実",
      "情",
      "報",
      "伝",
      "方",
      "最",
      "重",
      "要",
      "考",
      "将",
      "来",
      "予",
      "測",
      "際",
      "断",
      "定",
      "避",
      "自",
      "信",
      "受",
      "取",
      "複",
      "雑",
      "条",
      "件",
      "省",
      "結",
      "論",
      "明",
      "快",
      "示",
      "隠",
      "説",
      "明",
      "短",
      "期",
      "的",
      "理",
      "解",
      "外",
      "信",
      "頼",
      "大",
      "損",
      "可",
      "能",
      "性",
      "全",
      "並",
      "細",
      "例",
      "外",
      "羅",
      "列",
      "基",
      "準",
      "行",
      "動",
      "分",
      "誠",
      "実",
      "判",
      "断",
      "相",
      "手",
      "丸",
      "投",
      "同",
      "必",
      "要",
      "比",
      "較",
      "部",
      "分",
      "左",
      "右",
      "状",
      "況",
      "変",
      "指",
      "標",
      "見",
      "直",
      "区",
      "別",
      "例",
      "必",
      "起",
      "二",
      "択",
      "現",
      "時",
      "点",
      "高",
      "通",
      "要",
      "因",
      "受",
      "手",
      "応",
      "更",
      "新",
      "迷",
      "境",
      "界",
      "共",
      "有",
    ],
  },
  {
    id: "n1-reading-grant",
    level: "N1",
    skill: "reading",
    officialType: "information-retrieval",
    instruction: "Use the grant guide to answer the question.",
    stem: "大学院生の森さんは、地域団体と協力して聞き取り調査を六月から始めたい。調査費は十八万円で、研究成果を十一月の公開報告会で発表できる。応募条件を満たす枠の組み合わせはどれか。",
    passage: {
      title: "若手研究者支援制度",
      body: "【基礎調査枠】上限20万円／実施期間 6月1日〜翌年2月末／大学院生可／成果報告書を年度末までに提出\n【共同研究枠】上限80万円／実施期間 7月1日〜翌年3月末／2機関以上の研究者で申請／中間報告会あり\n【地域連携枠】上限30万円／実施期間 5月15日〜11月30日／地域団体との協力必須／11月の公開報告会で発表\n【試行枠】上限10万円／実施期間は採択後3か月以内／新規手法の予備実験に限る\n※同一テーマで複数枠への応募は不可。地域連携枠の申請には、協力団体の同意書を添付すること。",
    },
    options: options(
      "基礎調査枠のみ",
      "地域連携枠のみ",
      "基礎調査枠と地域連携枠",
      "地域連携枠と試行枠",
    ),
    correctOptionId: "3",
    explanation:
      "The basic-research slot allows graduate students, June starts, and up to 200,000 yen. The regional slot also fits the timing, budget, public presentation, and stated regional cooperation. The trial slot is capped at 100,000 yen. The applicant meets two sets of conditions but may submit only one application for the same theme.",
    relatedKanji: [
      "大",
      "学",
      "院",
      "生",
      "森",
      "地",
      "域",
      "聞",
      "取",
      "調",
      "査",
      "六",
      "月",
      "始",
      "費",
      "十",
      "八",
      "万",
      "円",
      "研",
      "究",
      "成",
      "果",
      "十",
      "一",
      "公",
      "開",
      "報",
      "告",
      "会",
      "発",
      "表",
      "応",
      "募",
      "枠",
      "若",
      "手",
      "者",
      "支",
      "援",
      "制",
      "度",
      "基",
      "礎",
      "上",
      "限",
      "実",
      "施",
      "期",
      "間",
      "翌",
      "年",
      "末",
      "可",
      "提",
      "出",
      "共",
      "同",
      "機",
      "関",
      "以",
      "上",
      "申",
      "請",
      "中",
      "連",
      "携",
      "団",
      "体",
      "協",
      "力",
      "必",
      "須",
      "試",
      "行",
      "採",
      "択",
      "後",
      "以",
      "内",
      "新",
      "規",
      "手",
      "法",
      "予",
      "備",
      "験",
      "限",
      "同",
      "一",
      "複",
      "数",
      "不",
      "可",
      "意",
      "書",
      "添",
      "付",
    ],
  },
  {
    id: "n1-listening-task-panel",
    level: "N1",
    skill: "listening",
    officialType: "listening-task",
    shortQuiz: true,
    instruction: "Listen and choose what the woman will do first.",
    stem: "女の人は、まず何をしますか。",
    listening: {
      script:
        "男の人：来週のシンポジウム、登壇者が一人来られなくなりましたね。\n女の人：はい。プログラムを短くして、討論の時間を延ばそうと思います。\n男の人：会場への連絡より先に、ほかの登壇者の了承を取ってください。時間変更が難しい方がいるかもしれません。\n女の人：分かりました。返事がそろったら会場に伝えます。",
      maxPlays: 2,
      rate: 1.1,
    },
    options: options(
      "プログラムを印刷する",
      "会場へ時間変更を連絡する",
      "ほかの登壇者に変更の了承を求める",
      "新しい登壇者を探す",
    ),
    correctOptionId: "3",
    explanation:
      "The man explicitly says to obtain the other speakers' approval before contacting the venue.",
    relatedKanji: [
      "女",
      "男",
      "来",
      "週",
      "登",
      "壇",
      "者",
      "一",
      "人",
      "短",
      "討",
      "論",
      "時",
      "間",
      "延",
      "思",
      "会",
      "場",
      "連",
      "絡",
      "先",
      "了",
      "承",
      "取",
      "変",
      "更",
      "難",
      "方",
      "分",
      "返",
      "事",
      "伝",
      "求",
      "新",
      "探",
    ],
  },
  {
    id: "n1-listening-key-budget",
    level: "N1",
    skill: "listening",
    officialType: "listening-key-points",
    shortQuiz: true,
    instruction: "Read the question, listen, and choose the correct answer.",
    stem: "研究所は来年度、広報誌をどうしますか。",
    listening: {
      script:
        "女の人：来年度は予算が一割減るそうですが、広報誌の発行回数を減らしますか。\n男の人：回数は維持したいです。印刷部数を減らし、希望者には電子版を案内しましょう。\n女の人：全員を電子版に切り替えるのではないんですね。\n男の人：ええ。紙が必要な施設には引き続き送ります。",
      maxPlays: 2,
      rate: 1.1,
    },
    options: options(
      "発行回数を減らす",
      "発行をすべて電子版にする",
      "回数は保ち、紙の部数を減らす",
      "紙の部数も回数も変えない",
    ),
    correctOptionId: "3",
    explanation:
      "They keep the publication frequency but reduce print quantity and guide willing readers to the digital edition.",
    relatedKanji: [
      "研",
      "究",
      "所",
      "来",
      "年",
      "度",
      "広",
      "報",
      "誌",
      "女",
      "予",
      "算",
      "一",
      "割",
      "減",
      "発",
      "行",
      "回",
      "数",
      "男",
      "維",
      "持",
      "印",
      "刷",
      "部",
      "希",
      "望",
      "者",
      "電",
      "子",
      "版",
      "案",
      "内",
      "全",
      "員",
      "切",
      "替",
      "紙",
      "必",
      "要",
      "施",
      "設",
      "引",
      "続",
      "送",
      "保",
      "変",
    ],
  },
  {
    id: "n1-listening-outline-incidents",
    level: "N1",
    skill: "listening",
    officialType: "listening-outline",
    instruction: "Listen to the talk, then choose its main point.",
    stem: "講師が最も伝えたいことは何ですか。",
    listening: {
      script:
        "事故の報告制度を作っても、報告した人が責められる職場では情報は集まりません。大きな事故だけを分析するのでは遅いのです。操作を間違えかけたが直前で気づいた、手順が紛らわしかった、といった小さな出来事を共有できれば、事故になる前に仕組みを直せます。重要なのは、個人の注意不足を探すことより、同じ間違いが起こりにくい環境を作ることです。\n講師が最も伝えたいことは何ですか。\n一、大事故を起こした個人を早く特定するべきだ。\n二、小さな失敗の兆候を安心して共有し、仕組みの改善に使うべきだ。\n三、報告制度より個人の注意力を高める訓練が重要だ。\n四、事故の報告件数を減らすことを目標にすべきだ。",
      audioOnlyOptions: true,
      maxPlays: 2,
      rate: 1.1,
    },
    options: options(
      "大事故を起こした個人を早く特定するべきだ",
      "小さな失敗の兆候を安心して共有し、仕組みの改善に使うべきだ",
      "報告制度より個人の注意力を高める訓練が重要だ",
      "事故の報告件数を減らすことを目標にすべきだ",
    ),
    correctOptionId: "2",
    explanation:
      "The speaker advocates a blame-light reporting culture that captures near misses and improves systems before serious accidents.",
    relatedKanji: [
      "講",
      "師",
      "最",
      "伝",
      "事",
      "故",
      "報",
      "告",
      "制",
      "度",
      "作",
      "人",
      "責",
      "職",
      "場",
      "情",
      "報",
      "集",
      "大",
      "分",
      "析",
      "遅",
      "操",
      "作",
      "間",
      "違",
      "直",
      "前",
      "気",
      "手",
      "順",
      "紛",
      "小",
      "出",
      "来",
      "共",
      "有",
      "前",
      "仕",
      "組",
      "直",
      "重",
      "要",
      "個",
      "人",
      "注",
      "意",
      "不",
      "足",
      "探",
      "同",
      "起",
      "環",
      "境",
    ],
  },
  {
    id: "n1-listening-quick-reschedule",
    level: "N1",
    skill: "listening",
    officialType: "listening-quick-response",
    shortQuiz: true,
    instruction: "Listen and choose the best response.",
    stem: "最も適切な答えを選んでください。",
    listening: {
      script:
        "先方から、打ち合わせを一週間延期できないかとのことです。\n一、では、こちらの予定を確認して返答します。\n二、一週間前に打ち合わせました。\n三、先方には延期しないとのことでした。",
      audioOnlyOptions: true,
      maxPlays: 2,
      rate: 1.1,
    },
    options: options("1", "2", "3"),
    correctOptionId: "1",
    explanation:
      "Checking one's schedule before replying is the appropriate response to a request to postpone the meeting.",
    relatedKanji: [
      "最",
      "適",
      "切",
      "答",
      "先",
      "方",
      "打",
      "合",
      "一",
      "週",
      "間",
      "延",
      "期",
      "予",
      "定",
      "確",
      "認",
      "返",
      "答",
      "前",
    ],
  },
  {
    id: "n1-listening-integrated-exhibit",
    level: "N1",
    skill: "listening",
    officialType: "listening-integrated",
    instruction: "Listen to the discussion and choose the plan they decide on.",
    stem: "博物館は新しい展示をどのように直しますか。",
    listening: {
      script:
        "男の人：試験公開のアンケートでは、映像は好評でしたが、説明が長くて順路が分かりにくいという意見が多いですね。\n女の人：映像を短くするより、説明を二段階にしませんか。入口には要点だけを置き、詳しい内容は奥で読めるようにするんです。\n男の人：順路は床の印を増やせばよさそうです。映像は今の長さを保つということですね。\n女の人：はい。見たい人が内容を選べる構成にしましょう。\n博物館は新しい展示をどのように直しますか。\n一、映像を短くし、説明をすべて入口へ移す。\n二、映像をなくし、床の印だけを増やす。\n三、映像は保ち、説明を要点と詳細に分け、順路表示を増やす。\n四、展示の順番を逆にし、説明を長くする。",
      audioOnlyOptions: true,
      maxPlays: 2,
      rate: 1.1,
    },
    options: options(
      "映像を短くし、説明をすべて入口へ移す",
      "映像をなくし、床の印だけを増やす",
      "映像は保ち、説明を要点と詳細に分け、順路表示を増やす",
      "展示の順番を逆にし、説明を長くする",
    ),
    correctOptionId: "3",
    explanation:
      "They retain the video, layer the explanation into summary and detail, and add floor markers for the route.",
    relatedKanji: [
      "博",
      "物",
      "館",
      "新",
      "展",
      "示",
      "直",
      "男",
      "試",
      "験",
      "公",
      "開",
      "映",
      "像",
      "好",
      "評",
      "説",
      "明",
      "長",
      "順",
      "路",
      "分",
      "意",
      "見",
      "多",
      "女",
      "短",
      "二",
      "段",
      "階",
      "入",
      "口",
      "要",
      "点",
      "置",
      "詳",
      "内",
      "容",
      "奥",
      "読",
      "床",
      "印",
      "増",
      "今",
      "保",
      "見",
      "人",
      "選",
      "構",
      "成",
    ],
  },
];

export const N1_QUESTIONS: readonly JlptQuestion[] = [
  ...N1_AUTHORED_QUESTIONS,
  ...N1_GENERATED_QUESTIONS,
];
