import type { JlptQuestion } from "../types";
import { N2_GENERATED_QUESTIONS } from "./generated/n2.generated";

const options = (...labels: string[]) =>
  labels.map((label, index) => ({ id: String(index + 1), label }));

const N2_AUTHORED_QUESTIONS: readonly JlptQuestion[] = [
  {
    id: "n2-kanji-shinchou",
    level: "N2",
    skill: "kanji",
    officialType: "kanji-reading",
    shortQuiz: true,
    instruction: "Choose the correct reading for the underlined word.",
    stem: "重要な契約なので、慎重に確認してください。",
    focus: "慎重",
    options: options("しんじゅう", "しんちょう", "しんしょう", "しんじょう"),
    correctOptionId: "2",
    explanation: "慎重 is read しんちょう and means careful or prudent.",
    relatedKanji: ["重", "要", "契", "約", "慎", "確", "認"],
  },
  {
    id: "n2-kanji-moyoosu",
    level: "N2",
    skill: "kanji",
    officialType: "kanji-reading",
    instruction: "Choose the correct reading for the underlined word.",
    stem: "来月、この町で国際会議が催されます。",
    focus: "催されます",
    options: options(
      "うながされます",
      "もよおされます",
      "そなえられます",
      "まかなわれます",
    ),
    correctOptionId: "2",
    explanation:
      "催す is read もよおす and means to hold or organize an event.",
    relatedKanji: ["来", "月", "町", "国", "際", "会", "議", "催"],
  },
  {
    id: "n2-orthography-kouken",
    level: "N2",
    skill: "kanji",
    officialType: "orthography",
    shortQuiz: true,
    instruction: "Choose the best writing for the hiragana word.",
    stem: "この研究は医療の発展に大きく こうけんした。",
    focus: "こうけん",
    options: options("貢献", "貢健", "項献", "講献"),
    correctOptionId: "1",
    explanation: "こうけん, a contribution, is written 貢献.",
    relatedKanji: ["研", "究", "医", "療", "発", "展", "大", "貢", "献"],
  },
  {
    id: "n2-word-formation-reuse",
    level: "N2",
    skill: "vocabulary",
    officialType: "word-formation",
    instruction: "Choose the element that completes the word in context.",
    stem: "資源を大切にするため、この工場では水を再＿＿しています。",
    options: options("開", "会", "利用", "度"),
    correctOptionId: "3",
    explanation:
      "再利用 means reuse. 再開 and 再会 are valid words, but neither can take 水を in this meaning.",
    relatedKanji: ["資", "源", "大", "切", "工", "場", "水", "再", "利", "用"],
  },
  {
    id: "n2-context-miotosu",
    level: "N2",
    skill: "vocabulary",
    officialType: "context-expression",
    shortQuiz: true,
    instruction: "Choose the word that best completes the sentence.",
    stem: "何度も資料を確認したのに、小さな数字の間違いを＿＿しまった。",
    options: options("見上げて", "見落として", "見送って", "見直して"),
    correctOptionId: "2",
    explanation:
      "見落とす means to overlook or fail to notice something. The speaker checked but still missed the error.",
    relatedKanji: [
      "何",
      "度",
      "資",
      "料",
      "確",
      "認",
      "小",
      "数",
      "字",
      "間",
      "違",
      "見",
      "落",
    ],
  },
  {
    id: "n2-context-ainiku",
    level: "N2",
    skill: "vocabulary",
    officialType: "context-expression",
    instruction: "Choose the word that best completes the sentence.",
    stem: "せっかくお越しいただきましたが、担当者は＿＿外出しております。",
    options: options("あいにく", "さすがに", "むしろ", "いよいよ"),
    correctOptionId: "1",
    explanation:
      "あいにく politely signals an unfortunate circumstance: the person in charge is out despite the visit.",
    relatedKanji: ["越", "担", "当", "者", "外", "出"],
  },
  {
    id: "n2-paraphrase-uchikiru",
    level: "N2",
    skill: "vocabulary",
    officialType: "paraphrase",
    shortQuiz: true,
    instruction: "Choose the expression with nearly the same meaning.",
    stem: "雨が強くなったため、試合は途中で打ち切られた。",
    focus: "打ち切られた",
    options: options(
      "予定より早く終わった",
      "別の場所で続けられた",
      "しばらく休んで再開した",
      "参加者が増やされた",
    ),
    correctOptionId: "1",
    explanation:
      "打ち切る means to bring something to an end before its planned completion.",
    relatedKanji: [
      "雨",
      "強",
      "試",
      "合",
      "途",
      "中",
      "打",
      "切",
      "予",
      "定",
      "早",
      "終",
    ],
  },
  {
    id: "n2-usage-unagasu",
    level: "N2",
    skill: "vocabulary",
    officialType: "usage",
    instruction:
      "Choose the sentence in which the underlined word is used correctly.",
    stem: "促す",
    options: options(
      "係員は、入口で立ち止まらないよう客に移動を促した。",
      "窓を開けて、部屋の空気を促した。",
      "雨が促したので、試合は中止になった。",
      "この薬は一日に二回促してください。",
    ),
    correctOptionId: "1",
    explanation:
      "促す means to urge or encourage an action. The staff member urges visitors to keep moving.",
    relatedKanji: ["促", "係", "員", "入", "口", "立", "止", "客", "移", "動"],
  },
  {
    id: "n2-grammar-kanenai",
    level: "N2",
    skill: "grammar",
    officialType: "grammar-form",
    shortQuiz: true,
    instruction: "Choose the form that best completes the sentence.",
    stem: "このまま雨が降り続けば、川があふれ＿＿。",
    options: options(
      "かねません",
      "きれません",
      "たまりません",
      "っこありません",
    ),
    correctOptionId: "1",
    explanation:
      "～かねない expresses that an undesirable outcome may occur. Flooding is a plausible negative consequence.",
    relatedKanji: ["雨", "降", "続", "川"],
  },
  {
    id: "n2-grammar-nichigainai",
    level: "N2",
    skill: "grammar",
    officialType: "grammar-form",
    instruction: "Choose the form that best completes the sentence.",
    stem: "電気がついているから、田中さんはまだ研究室にいる＿＿。",
    options: options(
      "にすぎない",
      "に違いない",
      "にもかかわらない",
      "にほかならないで",
    ),
    correctOptionId: "2",
    explanation:
      "～に違いない expresses the speaker's strong inference based on the light being on.",
    relatedKanji: ["電", "気", "田", "中", "研", "究", "室", "違"],
  },
  {
    id: "n2-composition-policy",
    level: "N2",
    skill: "grammar",
    officialType: "sentence-composition",
    shortQuiz: true,
    instruction:
      "Put the four parts in the correct order. Which part goes in ★?",
    stem: "新しい制度については　＿＿　＿＿　★　＿＿　予定だ。",
    options: options("市民の意見を", "うえで", "決定する", "聞いた"),
    correctOptionId: "2",
    sentenceComposition: {
      canonicalOrderOptionIds: ["1", "4", "2", "3"],
      starredPosition: 2,
    },
    explanation:
      "The natural order is 市民の意見を 聞いた うえで 決定する予定だ. Therefore うえで is in the starred third position.",
    relatedKanji: [
      "新",
      "制",
      "度",
      "市",
      "民",
      "意",
      "見",
      "聞",
      "決",
      "定",
      "予",
    ],
  },
  {
    id: "n2-text-grammar-remote",
    level: "N2",
    skill: "grammar",
    officialType: "text-grammar",
    instruction:
      "Read the passage and choose the expression that best fits the blank.",
    stem: "（　）に入るものとして、最もよいものを一つ選んでください。",
    passage: {
      body: "在宅勤務には、通勤時間を減らせるという利点がある。家族と過ごす時間が増えたという人も少なくない。＿＿、仕事と生活の区切りをつけにくく、長時間働いてしまうという声もある。企業には、利便性と負担の両方を考えた制度づくりが求められる。",
    },
    options: options("それどころか", "一方で", "したがって", "なぜなら"),
    correctOptionId: "2",
    explanation:
      "一方で introduces a contrasting disadvantage after the benefit.",
    relatedKanji: [
      "在",
      "宅",
      "勤",
      "務",
      "通",
      "時",
      "間",
      "減",
      "利",
      "点",
      "仕",
      "事",
      "生",
      "活",
      "区",
      "声",
      "企",
      "業",
      "両",
      "方",
      "考",
      "制",
      "度",
      "求",
    ],
  },
  {
    id: "n2-reading-feedback",
    level: "N2",
    skill: "reading",
    officialType: "reading-short",
    shortQuiz: true,
    instruction: "Read the passage and choose the correct answer.",
    stem: "筆者が会議で心がけていることは何ですか。",
    passage: {
      body: "会議で意見を求められたとき、私はすぐに賛成か反対かを言わないようにしている。まず、相手の提案を自分の言葉で短く言い直し、理解が合っているか確かめる。そのうえで意見を述べると、話し合いが感情的になりにくく、違いもはっきりするからだ。",
    },
    options: options(
      "相手より先に結論を言うこと",
      "提案を理解したか確かめてから意見を言うこと",
      "反対意見をできるだけ避けること",
      "会議では感情をまったく見せないこと",
    ),
    correctOptionId: "2",
    explanation:
      "The writer first restates the proposal to verify understanding, then gives an opinion.",
    relatedKanji: [
      "会",
      "議",
      "意",
      "見",
      "求",
      "私",
      "賛",
      "成",
      "反",
      "対",
      "相",
      "手",
      "提",
      "案",
      "自",
      "分",
      "言",
      "葉",
      "短",
      "直",
      "理",
      "解",
      "合",
      "確",
      "述",
      "話",
      "感",
      "情",
      "的",
      "違",
    ],
  },
  {
    id: "n2-reading-empty-space",
    level: "N2",
    skill: "reading",
    officialType: "reading-mid",
    instruction: "Read the passage and choose the best answer.",
    stem: "筆者が『何もしない時間』を予定に入れる理由は何ですか。",
    passage: {
      body: "予定表に空きがあると、つい別の用事を入れたくなる。しかし私は最近、週に一度は『何もしない時間』を先に予定に入れている。それは休むことだけが目的ではない。忙しい日々の中では、目の前の仕事を終わらせることに集中し、そもそも何を優先すべきかを考えなくなる。予定を入れない時間に散歩をしたり、ぼんやりしたりすると、急いでいるときには気づかなかった問題や考えが浮かぶことがある。もちろん、何も思いつかない日もある。それでも、すぐ役に立つ成果を求めずに考えを待つ時間は必要だと思う。",
    },
    options: options(
      "仕事を予定どおり終わらせるため",
      "休む時間を毎日同じにするため",
      "優先すべきことや新しい考えに気づく余地を作るため",
      "役に立つ成果を必ず得るため",
    ),
    correctOptionId: "3",
    explanation:
      "The unscheduled space lets the writer reconsider priorities and notice ideas or problems that busyness hides.",
    relatedKanji: [
      "予",
      "定",
      "表",
      "空",
      "別",
      "用",
      "事",
      "私",
      "最",
      "近",
      "週",
      "一",
      "度",
      "何",
      "時",
      "間",
      "先",
      "入",
      "休",
      "目",
      "的",
      "忙",
      "日",
      "中",
      "前",
      "仕",
      "終",
      "集",
      "優",
      "考",
      "散",
      "歩",
      "急",
      "気",
      "問",
      "題",
      "浮",
      "当",
      "然",
      "思",
      "立",
      "成",
      "果",
      "求",
      "待",
      "必",
      "要",
    ],
  },
  {
    id: "n2-reading-integrated-library",
    level: "N2",
    skill: "reading",
    officialType: "reading-integrated",
    instruction: "Read both opinions and choose what they agree on.",
    stem: "AさんとBさんが共通して述べていることは何ですか。",
    passage: {
      title: "市立図書館の開館時間について",
      body: "【Aさん】仕事の帰りに利用できるよう、平日は夜九時まで開けてほしい。ただし、利用者が少ない時間まで毎日開けるのは費用がかかるので、まず週二日から試してはどうか。\n\n【Bさん】夜の開館より、朝早く開けるほうが学生や高齢者には便利だと思う。職員を増やせないなら、曜日によって朝型と夜型を分け、実際の利用者数を調べるべきだ。",
    },
    options: options(
      "毎日夜九時まで開けるべきだ。",
      "朝早く開ける必要はない。",
      "時間を変えるなら、限定的に試して利用状況を確かめるべきだ。",
      "職員を増やしてから時間を変えるべきだ。",
    ),
    correctOptionId: "3",
    explanation:
      "Both propose a limited trial and checking actual use, even though A favors evenings and B also considers mornings.",
    relatedKanji: [
      "市",
      "立",
      "図",
      "書",
      "館",
      "開",
      "時",
      "間",
      "仕",
      "事",
      "帰",
      "利",
      "用",
      "平",
      "日",
      "夜",
      "九",
      "少",
      "毎",
      "費",
      "週",
      "二",
      "試",
      "朝",
      "早",
      "学",
      "生",
      "高",
      "齢",
      "者",
      "便",
      "職",
      "員",
      "増",
      "曜",
      "型",
      "分",
      "実",
      "際",
      "数",
      "調",
      "共",
      "通",
      "述",
    ],
  },
  {
    id: "n2-reading-thematic-efficiency",
    level: "N2",
    skill: "reading",
    officialType: "reading-thematic",
    instruction: "Read the passage and choose the writer's main claim.",
    stem: "筆者が最も言いたいことは何ですか。",
    passage: {
      body: "効率を上げるために、作業の手順を細かく決めることは有効だ。同じ失敗を防ぎ、経験の少ない人でも一定の成果を出しやすくなる。しかし、手順が詳しくなるほど、そこに書かれていない事態に対応できなくなる危険もある。\n大切なのは、手順を守ること自体を目的にしないことだ。なぜその順番なのか、どの失敗を防ぐためなのかを共有していれば、状況が変わったときにも判断できる。手順は判断の代わりではなく、判断を支える道具である。だから、手順を整えると同時に、その背景を説明し、現場からの疑問や改善案を受け取る仕組みが必要になる。",
    },
    options: options(
      "詳しい手順があれば、現場の判断は必要ない。",
      "経験の少ない人には手順を見せないほうがよい。",
      "手順は目的や背景とともに共有し、判断を支えるものとして使うべきだ。",
      "状況が変わるたびに、すべての手順を捨てるべきだ。",
    ),
    correctOptionId: "3",
    explanation:
      "The passage argues for procedures as support for informed judgment, paired with shared rationale and feedback.",
    relatedKanji: [
      "効",
      "率",
      "上",
      "作",
      "業",
      "手",
      "順",
      "細",
      "決",
      "有",
      "同",
      "失",
      "敗",
      "防",
      "経",
      "験",
      "少",
      "人",
      "一",
      "定",
      "成",
      "果",
      "出",
      "詳",
      "書",
      "事",
      "態",
      "対",
      "応",
      "危",
      "険",
      "大",
      "切",
      "守",
      "自",
      "体",
      "目",
      "的",
      "共",
      "有",
      "状",
      "況",
      "変",
      "判",
      "断",
      "代",
      "支",
      "道",
      "具",
      "整",
      "背",
      "景",
      "説",
      "明",
      "現",
      "場",
      "疑",
      "問",
      "改",
      "善",
      "案",
      "受",
      "取",
      "仕",
      "組",
      "必",
      "要",
    ],
  },
  {
    id: "n2-reading-seminar",
    level: "N2",
    skill: "reading",
    officialType: "information-retrieval",
    instruction: "Use the program to answer the question.",
    stem: "商品開発部の佐々木さんは、火曜日の午後に参加でき、少人数で実際に練習する講座を希望しています。どれが最も合いますか。",
    passage: {
      title: "社内研修プログラム",
      body: "A データから読む市場　月曜 10:00–12:00　定員40名　講義中心\nB 伝わる商品説明　火曜 13:30–16:30　定員12名　演習あり\nC 苦情対応の基本　火曜 9:00–12:00　定員20名　事例検討\nD 新人指導の進め方　水曜 14:00–17:00　定員10名　ロールプレイ\n※演習・ロールプレイの講座は、事前課題の提出が必要です。",
    },
    options: options("A", "B", "C", "D"),
    correctOptionId: "2",
    explanation:
      "B is Tuesday afternoon, has the smallest Tuesday-afternoon group, and explicitly includes hands-on exercises.",
    relatedKanji: [
      "商",
      "品",
      "開",
      "発",
      "部",
      "佐",
      "木",
      "火",
      "曜",
      "午",
      "後",
      "参",
      "加",
      "少",
      "人",
      "数",
      "実",
      "際",
      "練",
      "習",
      "講",
      "座",
      "希",
      "望",
      "合",
      "社",
      "内",
      "研",
      "修",
      "定",
      "員",
      "演",
    ],
  },
  {
    id: "n2-listening-task-venue",
    level: "N2",
    skill: "listening",
    officialType: "listening-task",
    shortQuiz: true,
    instruction: "Listen and choose what the woman will do first.",
    stem: "女の人は、まず何をしますか。",
    listening: {
      script:
        "男の人：明日の説明会、会場の準備は進んでいますか。\n女の人：資料と名札は用意できました。いすは業者が午後に並べます。\n男の人：では、参加者に会場変更のメールを送ってください。そのあと、受付の表示を作りましょう。\n女の人：わかりました。",
      maxPlays: 2,
      rate: 1.04,
    },
    options: options(
      "名札を用意する",
      "いすを並べる",
      "会場変更のメールを送る",
      "受付の表示を作る",
    ),
    correctOptionId: "3",
    explanation:
      "The materials and name tags are ready, and a contractor handles chairs. The first new task is sending the venue-change email.",
    relatedKanji: [
      "男",
      "女",
      "明",
      "日",
      "説",
      "明",
      "会",
      "場",
      "準",
      "備",
      "進",
      "資",
      "料",
      "名",
      "札",
      "用",
      "意",
      "業",
      "者",
      "午",
      "後",
      "並",
      "参",
      "加",
      "変",
      "更",
      "送",
      "受",
      "付",
      "表",
      "示",
      "作",
    ],
  },
  {
    id: "n2-listening-key-budget",
    level: "N2",
    skill: "listening",
    officialType: "listening-key-points",
    shortQuiz: true,
    instruction: "Read the question, listen, and choose the correct answer.",
    stem: "二人は広告費をどうすることにしましたか。",
    listening: {
      script:
        "女の人：来月のイベント、新聞広告は去年と同じ大きさで出しますか。\n男の人：効果があまり分からなかったので、小さくして、その分をインターネット広告に回したいです。\n女の人：新聞をやめるわけではないんですね。\n男の人：ええ。両方使って、反応を比べましょう。",
      maxPlays: 2,
      rate: 1.04,
    },
    options: options(
      "新聞広告だけを大きくする",
      "新聞広告をやめる",
      "新聞広告を小さくし、ネット広告にも費用を使う",
      "広告費全体を使わない",
    ),
    correctOptionId: "3",
    explanation:
      "They keep a smaller newspaper ad and shift the saved amount to online advertising so they can compare responses.",
    relatedKanji: [
      "二",
      "人",
      "広",
      "告",
      "費",
      "来",
      "月",
      "新",
      "聞",
      "去",
      "年",
      "同",
      "大",
      "出",
      "効",
      "果",
      "分",
      "小",
      "回",
      "両",
      "方",
      "使",
      "反",
      "応",
      "比",
    ],
  },
  {
    id: "n2-listening-outline-manager",
    level: "N2",
    skill: "listening",
    officialType: "listening-outline",
    instruction: "Listen to the talk, then choose its main point.",
    stem: "部長が最も伝えたいことは何ですか。",
    listening: {
      script:
        "新しい相談窓口を始めて一か月がたちました。相談件数は予想より少ないですが、これは問題がないという意味ではありません。利用方法が十分知られていない可能性があります。まず各部署で案内をもう一度行い、そのうえで三か月後の件数と内容を見て、続け方を判断したいと思います。\n部長が最も伝えたいことは何ですか。\n一、相談窓口をすぐ廃止する。\n二、問題がないので案内をやめる。\n三、利用を周知してからデータを見て今後を判断する。\n四、相談内容を各部署に公開する。",
      audioOnlyOptions: true,
      maxPlays: 2,
      rate: 1.04,
    },
    options: options(
      "相談窓口をすぐ廃止する",
      "問題がないので案内をやめる",
      "利用を周知してからデータを見て今後を判断する",
      "相談内容を各部署に公開する",
    ),
    correctOptionId: "3",
    explanation:
      "The manager wants to publicize the service first, then evaluate counts and content after three months.",
    relatedKanji: [
      "部",
      "長",
      "最",
      "伝",
      "新",
      "相",
      "談",
      "窓",
      "口",
      "始",
      "一",
      "月",
      "件",
      "数",
      "予",
      "想",
      "少",
      "問",
      "題",
      "意",
      "味",
      "利",
      "用",
      "方",
      "法",
      "十",
      "分",
      "知",
      "可",
      "能",
      "性",
      "各",
      "署",
      "案",
      "内",
      "度",
      "行",
      "三",
      "後",
      "内",
      "容",
      "見",
      "続",
      "判",
      "断",
      "思",
    ],
  },
  {
    id: "n2-listening-quick-correction",
    level: "N2",
    skill: "listening",
    officialType: "listening-quick-response",
    shortQuiz: true,
    instruction: "Listen and choose the best response.",
    stem: "いちばん適切な答えを選んでください。",
    listening: {
      script:
        "先ほどお送りした資料ですが、一か所訂正があります。\n一、承知しました。どの部分でしょうか。\n二、資料は送らなくてもかまいません。\n三、訂正したことはありません。",
      audioOnlyOptions: true,
      maxPlays: 2,
      rate: 1.04,
    },
    options: options("1", "2", "3"),
    correctOptionId: "1",
    explanation:
      "Acknowledging the correction and asking which part is the appropriate professional response.",
    relatedKanji: [
      "先",
      "送",
      "資",
      "料",
      "一",
      "所",
      "訂",
      "正",
      "承",
      "知",
      "部",
      "分",
    ],
  },
  {
    id: "n2-listening-integrated-product",
    level: "N2",
    skill: "listening",
    officialType: "listening-integrated",
    instruction:
      "Listen to the discussion and choose the proposal they will adopt.",
    stem: "二人はどの案で進めますか。",
    listening: {
      script:
        "男の人：新商品の容器、紙にすれば環境にはいいですが、今より二割高くなります。\n女の人：全部を変えるのは難しいですね。まず小さいサイズだけ紙にして、客の反応を見ませんか。\n男の人：大きいサイズは今の容器のままですか。\n女の人：はい。ただ、説明を付けて、紙の容器を選ぶ理由が伝わるようにしましょう。\n男の人：それでいきましょう。\n二人はどの案で進めますか。\n一、全サイズをすぐ紙にする。\n二、小さいサイズだけ紙にして反応を見る。\n三、紙への変更を中止する。\n四、大きいサイズだけ紙にする。",
      audioOnlyOptions: true,
      maxPlays: 2,
      rate: 1.04,
    },
    options: options(
      "全サイズをすぐ紙にする",
      "小サイズだけ紙にして反応を見る",
      "紙への変更を中止する",
      "大サイズだけ紙にする",
    ),
    correctOptionId: "2",
    explanation:
      "They agree to test paper packaging only for the small size and observe customer reactions.",
    relatedKanji: [
      "二",
      "人",
      "案",
      "進",
      "男",
      "新",
      "商",
      "品",
      "容",
      "器",
      "紙",
      "環",
      "境",
      "今",
      "割",
      "高",
      "女",
      "全",
      "変",
      "難",
      "小",
      "客",
      "反",
      "応",
      "見",
      "大",
      "説",
      "明",
      "付",
      "選",
      "理",
      "由",
      "伝",
    ],
  },
];

export const N2_QUESTIONS: readonly JlptQuestion[] = [
  ...N2_AUTHORED_QUESTIONS,
  ...N2_GENERATED_QUESTIONS,
];
