import type { JlptQuestion } from "../types";
import { N3_GENERATED_QUESTIONS } from "./generated/n3.generated";

const options = (...labels: string[]) =>
  labels.map((label, index) => ({ id: String(index + 1), label }));

const N3_AUTHORED_QUESTIONS: readonly JlptQuestion[] = [
  {
    id: "n3-kanji-shitaku",
    level: "N3",
    skill: "kanji",
    officialType: "kanji-reading",
    shortQuiz: true,
    instruction: "Choose the correct reading for the underlined word.",
    stem: "出かける支度はもうできました。",
    focus: "支度",
    options: options("したく", "しど", "しだく", "したび"),
    correctOptionId: "1",
    explanation: "支度 is read したく and means preparation.",
    relatedKanji: ["出", "支", "度"],
  },
  {
    id: "n3-kanji-tsugou",
    level: "N3",
    skill: "kanji",
    officialType: "kanji-reading",
    instruction: "Choose the correct reading for the underlined word.",
    stem: "来週の水曜日は都合が悪いです。",
    focus: "都合",
    options: options("とごう", "つごう", "とあい", "つあい"),
    correctOptionId: "2",
    explanation:
      "都合 is read つごう. 都合が悪い means that the time or circumstances are inconvenient.",
    relatedKanji: ["来", "週", "水", "曜", "都", "合", "悪"],
  },
  {
    id: "n3-orthography-tsuzukeru",
    level: "N3",
    skill: "kanji",
    officialType: "orthography",
    shortQuiz: true,
    instruction: "Choose the best writing for the hiragana word.",
    stem: "雨が降っても、試合は つづけます。",
    focus: "つづけます",
    options: options("続けます", "続きます", "継けます", "付けます"),
    correctOptionId: "1",
    explanation:
      "The transitive verb つづける, “to continue something,” is written 続ける. 続く is intransitive.",
    relatedKanji: ["雨", "降", "試", "合", "続"],
  },
  {
    id: "n3-orthography-haba",
    level: "N3",
    skill: "kanji",
    officialType: "orthography",
    instruction: "Choose the best writing for the hiragana word.",
    stem: "この道は せまいので、車に気をつけてください。",
    focus: "せまい",
    options: options("細い", "狭い", "短い", "低い"),
    correctOptionId: "2",
    explanation: "せまい, meaning narrow or cramped, is written 狭い.",
    relatedKanji: ["道", "狭", "車", "気"],
  },
  {
    id: "n3-context-enki",
    level: "N3",
    skill: "vocabulary",
    officialType: "context-expression",
    shortQuiz: true,
    instruction: "Choose the word that best completes the sentence.",
    stem: "台風のため、明日の試合は来週に＿＿されました。",
    options: options("延期", "延長", "中止", "開始"),
    correctOptionId: "1",
    explanation:
      "延期 means postponement to a later date. 来週に explicitly identifies the new date, so 中止 (cancellation) is wrong.",
    relatedKanji: ["台", "風", "明", "日", "試", "合", "来", "週", "延", "期"],
  },
  {
    id: "n3-context-mayou",
    level: "N3",
    skill: "vocabulary",
    officialType: "context-expression",
    instruction: "Choose the word that best completes the sentence.",
    stem: "青いシャツと白いシャツのどちらを買うか＿＿います。",
    options: options("望んで", "疑って", "迷って", "飽きて"),
    correctOptionId: "3",
    explanation:
      "どちらを買うか迷う naturally describes being unable to choose between two options.",
    relatedKanji: ["青", "白", "買", "迷"],
  },
  {
    id: "n3-paraphrase-ooyoso",
    level: "N3",
    skill: "vocabulary",
    officialType: "paraphrase",
    shortQuiz: true,
    instruction: "Choose the expression with nearly the same meaning.",
    stem: "工事はおおよそ一か月で終わる予定です。",
    focus: "おおよそ",
    options: options("必ず", "だいたい", "ようやく", "少なくとも"),
    correctOptionId: "2",
    explanation:
      "おおよそ and だいたい both mean approximately in this sentence.",
    relatedKanji: ["工", "事", "一", "月", "終", "予", "定"],
  },
  {
    id: "n3-usage-torikesu",
    level: "N3",
    skill: "vocabulary",
    officialType: "usage",
    instruction:
      "Choose the sentence in which the underlined word is used correctly.",
    stem: "取り消す",
    options: options(
      "予定が変わったので、ホテルの予約を取り消した。",
      "黒板の字を取り消して、ノートに書いた。",
      "電気がまぶしいので、部屋を取り消した。",
      "忘れ物を駅まで取り消しに行った。",
    ),
    correctOptionId: "1",
    explanation:
      "取り消す means to cancel or revoke something such as a reservation, order, or decision.",
    relatedKanji: ["取", "消", "予", "定", "変", "予", "約"],
  },
  {
    id: "n3-usage-kakunin",
    level: "N3",
    skill: "vocabulary",
    officialType: "usage",
    instruction:
      "Choose the sentence in which the underlined word is used correctly.",
    stem: "確認",
    options: options(
      "答えを書く前に、名前を確認してください。",
      "風が強いので、窓を確認してあります。",
      "この薬を飲めば、熱が確認します。",
      "駅までの道を確認に歩きました。",
    ),
    correctOptionId: "1",
    explanation:
      "確認する means to check or verify. Checking one's name before writing is natural and complete.",
    relatedKanji: ["確", "認", "答", "書", "前", "名"],
  },
  {
    id: "n3-grammar-wake",
    level: "N3",
    skill: "grammar",
    officialType: "grammar-form",
    shortQuiz: true,
    instruction: "Choose the form that best completes the sentence.",
    stem: "甘い物が嫌いな＿＿が、健康のために食べすぎないようにしています。",
    options: options(
      "わけではありません",
      "はずがありません",
      "ことになりました",
      "ものではありません",
    ),
    correctOptionId: "1",
    explanation:
      "The speaker is not saying they dislike sweets; they simply limit them for health. ～わけではない expresses partial negation.",
    relatedKanji: ["甘", "物", "嫌", "健", "康", "食"],
  },
  {
    id: "n3-grammar-uchini",
    level: "N3",
    skill: "grammar",
    officialType: "grammar-form",
    instruction: "Choose the form that best completes the sentence.",
    stem: "温かい＿＿、このスープを飲んでください。",
    options: options("うちに", "ところで", "ために", "ばかりに"),
    correctOptionId: "1",
    explanation:
      "温かいうちに means while it is still warm, before the state changes.",
    relatedKanji: ["温", "飲"],
  },
  {
    id: "n3-composition-report",
    level: "N3",
    skill: "grammar",
    officialType: "sentence-composition",
    shortQuiz: true,
    instruction:
      "Put the four parts in the correct order. Which part goes in ★?",
    stem: "レポートは　＿＿　＿＿　★　＿＿　ください。",
    options: options("金曜日", "までに", "出して", "必ず"),
    correctOptionId: "2",
    sentenceComposition: {
      canonicalOrderOptionIds: ["4", "1", "2", "3"],
      starredPosition: 2,
    },
    explanation:
      "The natural order is 必ず 金曜日 までに 出してください, so までに is in the starred third position.",
    relatedKanji: ["必", "金", "曜", "日", "出"],
  },
  {
    id: "n3-text-grammar-market",
    level: "N3",
    skill: "grammar",
    officialType: "text-grammar",
    instruction:
      "Read the passage and choose the expression that best fits the blank.",
    stem: "（　）に入るものとして、最もよいものを一つ選んでください。",
    passage: {
      body: "この町に大きなスーパーができました。品物が多く、夜遅くまで開いているので便利です。＿＿、店の人と話しながら買い物ができるため、昔からある小さい店に行く人もまだ多いです。町には、それぞれの店のよさを残したいという声があります。",
    },
    options: options("そのため", "つまり", "一方で", "たとえば"),
    correctOptionId: "3",
    explanation:
      "一方で introduces the contrasting fact that many people still visit the older small shops.",
    relatedKanji: [
      "町",
      "大",
      "品",
      "物",
      "多",
      "夜",
      "遅",
      "開",
      "便",
      "利",
      "昔",
      "小",
      "店",
      "行",
      "人",
      "一",
      "方",
    ],
  },
  {
    id: "n3-reading-email",
    level: "N3",
    skill: "reading",
    officialType: "reading-short",
    shortQuiz: true,
    instruction: "Read the email and choose the correct answer.",
    stem: "山本さんは佐藤さんに何を頼んでいますか。",
    passage: {
      title: "佐藤さんへ",
      body: "明日の会議ですが、急な出張で参加できなくなりました。机の上に資料を置いてありますので、会議の前に参加者へ配っていただけませんか。来週、内容を教えてください。山本",
    },
    options: options(
      "出張の予定を変えること",
      "会議に参加しないこと",
      "会議前に資料を配ること",
      "来週の会議を開くこと",
    ),
    correctOptionId: "3",
    explanation:
      "山本 asks 参加者へ配っていただけませんか, requesting that Sato distribute the materials before the meeting.",
    relatedKanji: [
      "山",
      "本",
      "佐",
      "藤",
      "明",
      "日",
      "会",
      "議",
      "急",
      "出",
      "張",
      "参",
      "加",
      "机",
      "上",
      "資",
      "料",
      "置",
      "前",
      "者",
      "配",
      "来",
      "週",
      "内",
      "容",
      "教",
    ],
  },
  {
    id: "n3-reading-habit",
    level: "N3",
    skill: "reading",
    officialType: "reading-mid",
    shortQuiz: true,
    instruction: "Read the passage and choose the correct answer.",
    stem: "筆者は、朝の散歩についてどう考えていますか。",
    passage: {
      body: "会社まで電車で通っていたころ、私はほとんど運動をしていなかった。そこで半年前から、毎朝一つ手前の駅で降りて、二十分歩くことにした。最初は早く起きるのが大変だったが、今では季節の変化に気づくのが楽しい。体重はあまり変わらないが、午前中に集中しやすくなった。短い時間でも、続けることに意味があると思っている。",
    },
    options: options(
      "体重が減らないので、やめたい。",
      "長時間歩かなければ意味がない。",
      "季節を楽しめるが、仕事には役立たない。",
      "短くても続けることで良い変化があった。",
    ),
    correctOptionId: "4",
    explanation:
      "The writer reports better concentration and concludes that continuing even for a short time is meaningful.",
    relatedKanji: [
      "会",
      "社",
      "電",
      "車",
      "通",
      "私",
      "運",
      "動",
      "半",
      "年",
      "前",
      "毎",
      "朝",
      "一",
      "手",
      "駅",
      "降",
      "二",
      "十",
      "分",
      "歩",
      "最",
      "初",
      "早",
      "起",
      "大",
      "変",
      "今",
      "季",
      "節",
      "化",
      "気",
      "楽",
      "体",
      "重",
      "午",
      "中",
      "集",
      "続",
      "意",
      "味",
      "思",
    ],
  },
  {
    id: "n3-reading-community",
    level: "N3",
    skill: "reading",
    officialType: "reading-long",
    instruction: "Read the passage and choose the best summary.",
    stem: "この文章の内容に最も合うものはどれですか。",
    passage: {
      body: "私の町では、使わなくなった物を交換する『交換会』が毎月開かれている。参加者は服や本、食器などを持ってきて、ほしい物があれば自由に持ち帰る。お金は使わない。\n初めは、ごみを減らすことが目的だった。しかし、続けているうちに別の良さも分かってきた。子どもの服を探していた人が、服を持ってきた家族から近くの公園の情報を聞くなど、物をきっかけに会話が生まれるのだ。一方で、壊れた物や汚れた物が集まる問題もあった。そこで今は、持ってくる前に状態を確認する決まりを作った。\n交換会は、不要な物を必要な人へ渡すだけでなく、住民同士が知り合う場所にもなっている。",
    },
    options: options(
      "交換会は、お金を集めて町のごみを処理する活動だ。",
      "交換会は、物の再利用と住民の交流の両方に役立っている。",
      "交換会では、壊れた物だけを修理して持ち帰る。",
      "交換会は問題が多かったため、今は開かれていない。",
    ),
    correctOptionId: "2",
    explanation:
      "The final paragraph states both functions: passing unneeded things to people who need them and helping residents get to know each other.",
    relatedKanji: [
      "私",
      "町",
      "使",
      "物",
      "交",
      "換",
      "会",
      "毎",
      "月",
      "開",
      "参",
      "加",
      "者",
      "服",
      "本",
      "食",
      "器",
      "持",
      "自",
      "由",
      "帰",
      "金",
      "初",
      "減",
      "目",
      "的",
      "続",
      "別",
      "良",
      "分",
      "子",
      "探",
      "人",
      "家",
      "族",
      "近",
      "公",
      "園",
      "情",
      "報",
      "聞",
      "話",
      "生",
      "一",
      "方",
      "壊",
      "汚",
      "集",
      "問",
      "題",
      "前",
      "状",
      "態",
      "確",
      "認",
      "決",
      "作",
      "不",
      "要",
      "必",
      "住",
      "民",
      "同",
      "士",
      "知",
      "場",
      "所",
    ],
  },
  {
    id: "n3-reading-course",
    level: "N3",
    skill: "reading",
    officialType: "information-retrieval",
    instruction: "Use the course guide to answer the question.",
    stem: "会社員のリーさんは平日の午後七時以降に参加したいです。料理は初めてですが、全四回参加できます。どの講座が合いますか。",
    passage: {
      title: "市民センター 秋の講座",
      body: "A はじめての和食　火曜 19:30〜21:00　全4回　初心者向け\nB 週末のパン作り　土曜 10:00〜12:30　全3回　経験者向け\nC 写真さんぽ　水曜 18:00〜20:00　全4回　どなたでも\nD 家庭料理の工夫　木曜 19:00〜21:00　全6回　料理経験がある方\n※欠席が2回以上の場合、修了証は出ません。",
    },
    options: options("A", "B", "C", "D"),
    correctOptionId: "1",
    explanation:
      "A starts after 7 p.m., has four sessions, and is explicitly for beginners. D requires cooking experience and has six sessions.",
    relatedKanji: [
      "会",
      "社",
      "員",
      "平",
      "日",
      "午",
      "後",
      "七",
      "時",
      "以",
      "降",
      "参",
      "加",
      "料",
      "理",
      "初",
      "全",
      "四",
      "回",
      "講",
      "座",
      "合",
      "市",
      "民",
      "秋",
      "和",
      "食",
      "火",
      "曜",
      "初",
      "心",
      "者",
      "向",
    ],
  },
  {
    id: "n3-listening-library",
    level: "N3",
    skill: "listening",
    officialType: "listening-task",
    shortQuiz: true,
    instruction: "Listen and choose what the man will do first.",
    stem: "男の人は、まず何をしますか。",
    listening: {
      script:
        "女の人：図書館のイベントの準備、どうですか。\n男の人：いすは並べました。資料はまだです。\n女の人：じゃあ、資料を二十部コピーしてください。そのあと、入口に案内を貼りましょう。\n男の人：はい。",
      maxPlays: 2,
      rate: 0.98,
    },
    options: options(
      "いすを並べる",
      "資料を二十部コピーする",
      "入口に案内を貼る",
      "図書館へ資料を返す",
    ),
    correctOptionId: "2",
    explanation:
      "The chairs are already arranged. The next instruction is to copy twenty sets of materials.",
    relatedKanji: [
      "女",
      "男",
      "図",
      "書",
      "館",
      "準",
      "備",
      "並",
      "資",
      "料",
      "二",
      "十",
      "部",
      "入",
      "口",
      "案",
      "内",
      "貼",
    ],
  },
  {
    id: "n3-listening-key-delivery",
    level: "N3",
    skill: "listening",
    officialType: "listening-key-points",
    instruction: "Read the question, listen, and choose the correct answer.",
    stem: "荷物はいつ届きますか。",
    listening: {
      script:
        "男の人：注文した机、金曜日に届く予定でしたよね。\n女の人：申し訳ありません。工場からの出荷が一日遅れまして、土曜日になります。午前と午後、どちらがよろしいですか。\n男の人：午後でお願いします。",
      maxPlays: 2,
      rate: 0.98,
    },
    options: options(
      "金曜日の午前",
      "金曜日の午後",
      "土曜日の午前",
      "土曜日の午後",
    ),
    correctOptionId: "4",
    explanation:
      "The shipment is delayed until Saturday, and the man chooses the afternoon.",
    relatedKanji: [
      "荷",
      "物",
      "届",
      "男",
      "注",
      "文",
      "机",
      "金",
      "曜",
      "予",
      "定",
      "女",
      "申",
      "訳",
      "工",
      "場",
      "出",
      "一",
      "日",
      "遅",
      "土",
      "午",
      "前",
      "後",
      "願",
    ],
  },
  {
    id: "n3-listening-outline-volunteer",
    level: "N3",
    skill: "listening",
    officialType: "listening-outline",
    instruction: "Listen to the talk, then choose its main point.",
    stem: "話の中心は何ですか。",
    listening: {
      script:
        "今日は川のそうじに参加してくださって、ありがとうございます。午前中は川の近くのごみを集めます。昼休みのあと、ごみを種類ごとに分けます。暑くなるかもしれませんので、無理をせず、水を飲みながら作業してください。\n話の中心は何ですか。\n一、川で泳ぐときの注意。\n二、そうじ活動の流れと注意。\n三、ごみの種類の説明。\n四、午後の天気の予報。",
      audioOnlyOptions: true,
      maxPlays: 2,
      rate: 0.98,
    },
    options: options(
      "川で泳ぐときの注意",
      "そうじ活動の流れと注意",
      "ごみの種類の説明",
      "午後の天気の予報",
    ),
    correctOptionId: "2",
    explanation:
      "The speaker explains the cleanup schedule and warns participants to hydrate and avoid overexertion.",
    relatedKanji: [
      "今",
      "日",
      "川",
      "参",
      "加",
      "午",
      "前",
      "中",
      "近",
      "集",
      "昼",
      "休",
      "種",
      "類",
      "分",
      "暑",
      "無",
      "理",
      "水",
      "飲",
      "作",
      "業",
    ],
  },
  {
    id: "n3-listening-verbal-photo",
    level: "N3",
    skill: "listening",
    officialType: "listening-verbal",
    instruction:
      "Look at the illustration, listen to the situation and three expressions, and choose the best one.",
    stem: "観光地で、知らない人に自分たちの写真を撮ってもらいたいです。何と言いますか。",
    listening: {
      script:
        "観光地で、女の人が知らない人に自分たちの写真を撮ってもらいたいです。何と言いますか。\n一、写真を撮っていただけませんか。\n二、写真を見せていただきました。\n三、写真を撮らせてしまいました。",
      audioOnlyOptions: true,
      verbalScene: {
        setting: "landmark",
        speaker: { side: "left", pose: "requesting" },
        partner: { side: "right", pose: "neutral" },
        prop: { kind: "camera", position: "center" },
        description:
          "At a sightseeing spot, a traveler holds out a camera and asks a nearby person for help.",
      },
      maxPlays: 2,
      rate: 0.96,
    },
    options: options(
      "写真を撮っていただけませんか。",
      "写真を見せていただきました。",
      "写真を撮らせてしまいました。",
    ),
    correctOptionId: "1",
    explanation:
      "～ていただけませんか is the appropriate polite request for someone to take the photo.",
    relatedKanji: [
      "観",
      "光",
      "地",
      "知",
      "人",
      "自",
      "分",
      "写",
      "真",
      "撮",
      "何",
      "言",
    ],
  },
  {
    id: "n3-listening-quick-borrow",
    level: "N3",
    skill: "listening",
    officialType: "listening-quick-response",
    shortQuiz: true,
    instruction: "Listen and choose the best response.",
    stem: "いちばんいい答えを選んでください。",
    listening: {
      script:
        "この辞書、ちょっと借りてもいいですか。\n一、ええ、どうぞ。\n二、いいえ、借りませんでした。\n三、辞書を買ったそうです。",
      audioOnlyOptions: true,
      maxPlays: 2,
      rate: 0.98,
    },
    options: options("1", "2", "3"),
    correctOptionId: "1",
    explanation:
      "ええ、どうぞ appropriately grants permission to borrow the dictionary.",
    relatedKanji: ["辞", "書", "借", "買"],
  },
];

export const N3_QUESTIONS: readonly JlptQuestion[] = [
  ...N3_AUTHORED_QUESTIONS.filter(
    (question) => question.officialType !== "listening-verbal",
  ),
  ...N3_GENERATED_QUESTIONS,
];
