import type { JlptQuestion } from "../types";
import { N4_GENERATED_QUESTIONS } from "./generated/n4.generated";

const options = (...labels: string[]) =>
  labels.map((label, index) => ({ id: String(index + 1), label }));

const N4_AUTHORED_QUESTIONS: readonly JlptQuestion[] = [
  {
    id: "n4-kanji-annai",
    level: "N4",
    skill: "kanji",
    officialType: "kanji-reading",
    shortQuiz: true,
    instruction: "Choose the correct reading for the underlined word.",
    stem: "駅まで案内してくれませんか。",
    focus: "案内",
    options: options("あんない", "あんだい", "あない", "あんねい"),
    correctOptionId: "1",
    explanation:
      "案内 is read あんない and means guidance or showing someone the way.",
    relatedKanji: ["駅", "案", "内"],
  },
  {
    id: "n4-kanji-untenshu",
    level: "N4",
    skill: "kanji",
    officialType: "kanji-reading",
    instruction: "Choose the correct reading for the underlined word.",
    stem: "父はバスの運転手です。",
    focus: "運転手",
    options: options(
      "うんてんしゅ",
      "うんどうしゅ",
      "うんてんて",
      "うんでんしゅ",
    ),
    correctOptionId: "1",
    explanation: "運転手 is read うんてんしゅ, “driver.”",
    relatedKanji: ["父", "運", "転", "手"],
  },
  {
    id: "n4-orthography-keshiki",
    level: "N4",
    skill: "kanji",
    officialType: "orthography",
    shortQuiz: true,
    instruction: "Choose the best writing for the hiragana word.",
    stem: "山の上から見た けしきは、とてもきれいでした。",
    focus: "けしき",
    options: options("景色", "京色", "影色", "景気"),
    correctOptionId: "1",
    explanation:
      "けしき (scenery) is written 景色. 景気 is read けいき and refers to economic conditions.",
    relatedKanji: ["山", "上", "見", "景", "色"],
  },
  {
    id: "n4-orthography-ryouri",
    level: "N4",
    skill: "kanji",
    officialType: "orthography",
    instruction: "Choose the best writing for the hiragana word.",
    stem: "姉は りょうりが とても上手です。",
    focus: "りょうり",
    options: options("料里", "料理", "科理", "科里"),
    correctOptionId: "2",
    explanation: "りょうり (cooking/cuisine) is written 料理.",
    relatedKanji: ["姉", "料", "理", "上", "手"],
  },
  {
    id: "n4-context-maniau",
    level: "N4",
    skill: "vocabulary",
    officialType: "context-expression",
    shortQuiz: true,
    instruction: "Choose the word that best completes the sentence.",
    stem: "今すぐ家を出れば、九時の電車に＿＿でしょう。",
    options: options("間に合う", "乗り換える", "通り過ぎる", "遅れる"),
    correctOptionId: "1",
    explanation:
      "間に合う means to be in time. Leaving now makes catching the nine o'clock train possible.",
    relatedKanji: ["今", "家", "出", "九", "時", "電", "車", "間", "合"],
  },
  {
    id: "n4-context-souvenir",
    level: "N4",
    skill: "vocabulary",
    officialType: "context-expression",
    instruction: "Choose the word that best completes the sentence.",
    stem: "旅行から帰った姉に、京都の＿＿をもらいました。",
    options: options("お祝い", "お見舞い", "お土産", "お礼"),
    correctOptionId: "3",
    explanation: "お土産 is a souvenir brought back from a trip.",
    relatedKanji: ["旅", "行", "帰", "姉", "京", "都", "土", "産"],
  },
  {
    id: "n4-paraphrase-shibaraku",
    level: "N4",
    skill: "vocabulary",
    officialType: "paraphrase",
    shortQuiz: true,
    instruction: "Choose the expression with nearly the same meaning.",
    stem: "ここでしばらく待っていてください。",
    focus: "しばらく",
    options: options("長い間", "少しの間", "夜まで", "一人で"),
    correctOptionId: "2",
    explanation: "しばらく means for a little while in this request.",
    relatedKanji: ["待", "長", "間", "少", "夜", "一", "人"],
  },
  {
    id: "n4-paraphrase-kondo",
    level: "N4",
    skill: "vocabulary",
    officialType: "paraphrase",
    instruction: "Choose the sentence with nearly the same meaning.",
    stem: "今度の日曜日に会いましょう。",
    focus: "今度の日曜日",
    options: options(
      "前の日曜日",
      "毎週の日曜日",
      "次の日曜日",
      "きのうの日曜日",
    ),
    correctOptionId: "3",
    explanation:
      "In this future invitation, 今度の日曜日 means the coming/next Sunday.",
    relatedKanji: ["今", "度", "日", "曜", "会", "前", "毎", "週", "次"],
  },
  {
    id: "n4-usage-nareru",
    level: "N4",
    skill: "vocabulary",
    officialType: "usage",
    instruction:
      "Choose the sentence in which the underlined word is used correctly.",
    stem: "慣れる",
    options: options(
      "新しい仕事に少しずつ慣れてきました。",
      "毎朝六時に慣れて学校へ行きます。",
      "この漢字を何回も慣れてください。",
      "雨が慣れたので出かけましょう。",
    ),
    correctOptionId: "1",
    explanation:
      "Xに慣れる means to become accustomed to X. Only the first sentence uses that pattern naturally.",
    relatedKanji: ["慣", "新", "仕", "事", "少"],
  },
  {
    id: "n4-grammar-nagara",
    level: "N4",
    skill: "grammar",
    officialType: "grammar-form",
    shortQuiz: true,
    instruction: "Choose the form that best completes the sentence.",
    stem: "妹は音楽を＿＿、宿題をしています。",
    options: options("聞くと", "聞いたら", "聞きながら", "聞くまで"),
    correctOptionId: "3",
    explanation:
      "The same person does both actions at once, so the verb stem + ながら is required.",
    relatedKanji: ["妹", "音", "楽", "聞", "宿", "題"],
  },
  {
    id: "n4-grammar-experience",
    level: "N4",
    skill: "grammar",
    officialType: "grammar-form",
    instruction: "Choose the form that best completes the sentence.",
    stem: "北海道へ行った＿＿がありますか。",
    options: options("もの", "こと", "ところ", "はず"),
    correctOptionId: "2",
    explanation: "Verb past form + ことがある asks about past experience.",
    relatedKanji: ["北", "海", "道", "行"],
  },
  {
    id: "n4-composition-library",
    level: "N4",
    skill: "grammar",
    officialType: "sentence-composition",
    shortQuiz: true,
    instruction:
      "Put the four parts in the correct order. Which part goes in ★?",
    stem: "図書館で　＿＿　＿＿　★　＿＿。",
    options: options("大きな声で", "話して", "は", "いけません"),
    correctOptionId: "3",
    sentenceComposition: {
      canonicalOrderOptionIds: ["1", "2", "3", "4"],
      starredPosition: 2,
    },
    explanation:
      "The natural sentence is 図書館で 大きな声で 話して は いけません. The starred third part is は.",
    relatedKanji: ["図", "書", "館", "大", "声", "話"],
  },
  {
    id: "n4-text-grammar-bicycle",
    level: "N4",
    skill: "grammar",
    officialType: "text-grammar",
    instruction:
      "Read the passage and choose the expression that best fits the blank.",
    stem: "（　）に入るものとして、最もよいものを一つ選んでください。",
    passage: {
      body: "駅まで歩くと二十分かかります。＿＿、自転車なら十分ぐらいで着きます。朝は時間がないので、いつも自転車で駅へ行きます。雨の日だけはバスを使います。",
    },
    options: options("それで", "しかし", "たとえば", "だから"),
    correctOptionId: "2",
    explanation:
      "しかし contrasts the 20-minute walk with the shorter 10-minute bicycle trip.",
    relatedKanji: ["駅", "歩", "二", "十", "分", "自", "転", "車"],
  },
  {
    id: "n4-reading-club",
    level: "N4",
    skill: "reading",
    officialType: "reading-short",
    shortQuiz: true,
    instruction: "Read the message and choose the correct answer.",
    stem: "雨のとき、テニスの練習はどうなりますか。",
    passage: {
      title: "テニス部のみなさんへ",
      body: "土曜日の練習は午前十時からです。雨のときは体育館で体力づくりをしますから、体育館のくつを持ってきてください。",
    },
    options: options(
      "休みになります。",
      "午後になります。",
      "体育館で運動します。",
      "教室で話を聞きます。",
    ),
    correctOptionId: "3",
    explanation:
      "The notice says that when it rains, the group will exercise in the gym.",
    relatedKanji: [
      "部",
      "土",
      "曜",
      "練",
      "習",
      "午",
      "前",
      "十",
      "時",
      "雨",
      "体",
      "育",
      "館",
      "運",
      "動",
      "持",
    ],
  },
  {
    id: "n4-reading-umbrella",
    level: "N4",
    skill: "reading",
    officialType: "reading-mid",
    instruction: "Read the passage and choose the correct answer.",
    stem: "木村さんがいちばん言いたいことは何ですか。",
    passage: {
      body: "わたしはよく物をわすれます。先週も電車の中にかさをわすれました。新しいかさを買いましたが、次の日、駅で前のかさが見つかったと電話がありました。かさが二本になったので、一本はいつも会社に置いておくことにしました。これでもう、急な雨でも困らないと思います。",
    },
    options: options(
      "電車にはかさを持って入らないほうがいい。",
      "見つかったかさを駅へ取りに行かない。",
      "会社にもかさを置いて、急な雨にそなえる。",
      "新しいかさを友だちにあげる。",
    ),
    correctOptionId: "3",
    explanation:
      "Kimura decides to keep one umbrella at work so unexpected rain will not be a problem.",
    relatedKanji: [
      "物",
      "先",
      "週",
      "電",
      "車",
      "中",
      "新",
      "買",
      "次",
      "日",
      "駅",
      "前",
      "見",
      "電",
      "話",
      "二",
      "本",
      "一",
      "会",
      "社",
      "置",
      "急",
      "雨",
      "困",
      "思",
    ],
  },
  {
    id: "n4-reading-pool",
    level: "N4",
    skill: "reading",
    officialType: "information-retrieval",
    instruction: "Use the schedule and rules to answer the question.",
    stem: "中学生の山田さんが水曜日の午後四時に泳ぐには、いくら必要ですか。",
    passage: {
      title: "市民プール",
      body: "開いている時間\n火〜金：午後一時〜八時　土・日：午前九時〜午後六時\n月曜日：休み\n料金\n大人 600円／高校生 400円／中学生以下 250円\n水曜日は学生証を見せると、学生は50円引きです。",
    },
    options: options("200円", "250円", "350円", "400円"),
    correctOptionId: "1",
    explanation:
      "The middle-school price is 250 yen, and Wednesday's student discount subtracts 50 yen: 200 yen.",
    relatedKanji: [
      "中",
      "学",
      "生",
      "山",
      "田",
      "水",
      "曜",
      "午",
      "後",
      "四",
      "時",
      "泳",
      "必",
      "要",
      "市",
      "民",
      "料",
      "金",
      "円",
      "証",
      "見",
      "引",
    ],
  },
  {
    id: "n4-listening-copy",
    level: "N4",
    skill: "listening",
    officialType: "listening-task",
    shortQuiz: true,
    instruction: "Listen and choose what the woman will do first.",
    stem: "女の人は、まず何をしますか。",
    listening: {
      script:
        "男の人：会議の資料、できましたか。\n女の人：はい、ここにあります。\n男の人：では、十人分コピーしてから、三階の会議室に持っていってください。\n女の人：わかりました。",
      maxPlays: 2,
      rate: 0.9,
    },
    options: options(
      "資料を作る",
      "資料を十人分コピーする",
      "三階へ行く",
      "会議を始める",
    ),
    correctOptionId: "2",
    explanation:
      "The instruction is コピーしてから…持っていって, so copying comes first.",
    relatedKanji: [
      "男",
      "女",
      "会",
      "議",
      "資",
      "料",
      "十",
      "人",
      "分",
      "三",
      "階",
      "室",
      "持",
    ],
  },
  {
    id: "n4-listening-appointment",
    level: "N4",
    skill: "listening",
    officialType: "listening-key-points",
    shortQuiz: true,
    instruction: "Read the question, listen, and choose the correct answer.",
    stem: "二人はいつ会いますか。",
    listening: {
      script:
        "女の人：金曜日の夕方、駅で会いませんか。\n男の人：金曜日は六時まで仕事なんです。土曜日の午前なら大丈夫です。\n女の人：土曜日は午後しか空いていません。\n男の人：では、土曜日の三時にしましょう。",
      maxPlays: 2,
      rate: 0.9,
    },
    options: options(
      "金曜日の六時",
      "土曜日の午前",
      "土曜日の三時",
      "日曜日の三時",
    ),
    correctOptionId: "3",
    explanation: "After comparing schedules, they agree on 土曜日の三時.",
    relatedKanji: [
      "二",
      "人",
      "会",
      "金",
      "曜",
      "夕",
      "方",
      "駅",
      "六",
      "時",
      "仕",
      "事",
      "土",
      "午",
      "前",
      "大",
      "丈",
      "夫",
      "後",
      "空",
      "三",
    ],
  },
  {
    id: "n4-listening-verbal-seat",
    level: "N4",
    skill: "listening",
    officialType: "listening-verbal",
    instruction:
      "Look at the illustration, listen to the situation and three expressions, and choose the best one.",
    stem: "電車でお年寄りに自分の席を使ってもらいます。何と言いますか。",
    listening: {
      script:
        "電車の中です。男の人がお年寄りに自分の席を使ってもらいたいです。何と言いますか。\n一、ここに座ってもいいですか。\n二、どうぞ、ここにお座りください。\n三、この席は座りません。",
      audioOnlyOptions: true,
      verbalScene: {
        setting: "train",
        speaker: { side: "left", pose: "offering" },
        partner: { side: "right", pose: "neutral" },
        prop: { kind: "seat", position: "center" },
        description:
          "On a train, a standing passenger gestures toward an empty seat for an older passenger.",
      },
      maxPlays: 2,
      rate: 0.88,
    },
    options: options(
      "ここに座ってもいいですか。",
      "どうぞ、ここにお座りください。",
      "この席は座りません。",
    ),
    correctOptionId: "2",
    explanation:
      "どうぞ、ここにお座りください politely offers the seat to the older person.",
    relatedKanji: [
      "電",
      "車",
      "年",
      "寄",
      "自",
      "分",
      "席",
      "使",
      "何",
      "言",
      "座",
    ],
  },
  {
    id: "n4-listening-quick-delay",
    level: "N4",
    skill: "listening",
    officialType: "listening-quick-response",
    shortQuiz: true,
    instruction: "Listen and choose the best response.",
    stem: "いちばんいい答えを選んでください。",
    listening: {
      script:
        "電車が遅れているそうですよ。\n一、では、少し早く家を出ましょう。\n二、いいえ、電車ではありません。\n三、さっき駅に着きましたか。",
      audioOnlyOptions: true,
      maxPlays: 2,
      rate: 0.9,
    },
    options: options("1", "2", "3"),
    correctOptionId: "1",
    explanation:
      "Leaving a little earlier is a sensible response to news that the train is delayed.",
    relatedKanji: ["電", "車", "遅", "少", "早", "家", "出", "駅", "着"],
  },
  {
    id: "n4-listening-gift",
    level: "N4",
    skill: "listening",
    officialType: "listening-task",
    instruction: "Listen and choose what the man will bring.",
    stem: "男の人は何を持っていきますか。",
    listening: {
      script:
        "女の人：日曜日のパーティー、飲み物はわたしが買います。\n男の人：じゃあ、食べ物を持っていきましょうか。\n女の人：ケーキは山田さんが作るそうです。果物をお願いできますか。\n男の人：わかりました。",
      maxPlays: 2,
      rate: 0.9,
    },
    options: options("飲み物", "ケーキ", "果物", "料理の本"),
    correctOptionId: "3",
    explanation: "The woman asks 果物をお願いできますか, and the man agrees.",
    relatedKanji: [
      "男",
      "女",
      "日",
      "曜",
      "飲",
      "買",
      "食",
      "物",
      "持",
      "山",
      "田",
      "作",
      "果",
      "願",
    ],
  },
];

export const N4_QUESTIONS: readonly JlptQuestion[] = [
  ...N4_AUTHORED_QUESTIONS.filter(
    (question) => question.officialType !== "listening-verbal",
  ),
  ...N4_GENERATED_QUESTIONS,
];
