import type { JlptQuestion } from "../types";
import { N5_GENERATED_QUESTIONS } from "./generated/n5.generated";

const options = (...labels: string[]) =>
  labels.map((label, index) => ({ id: String(index + 1), label }));

const N5_AUTHORED_QUESTIONS: readonly JlptQuestion[] = [
  {
    id: "n5-kanji-mainichi",
    level: "N5",
    skill: "kanji",
    officialType: "kanji-reading",
    shortQuiz: true,
    instruction: "Choose the correct reading for the underlined word.",
    stem: "毎朝、六時に起きます。",
    focus: "毎朝",
    options: options("まいあさ", "まいばん", "まいにち", "こんあさ"),
    correctOptionId: "1",
    explanation:
      "毎朝 is read まいあさ and means “every morning.” 毎日 is まいにち.",
    relatedKanji: ["毎", "朝"],
  },
  {
    id: "n5-kanji-matsu",
    level: "N5",
    skill: "kanji",
    officialType: "kanji-reading",
    instruction: "Choose the correct reading for the underlined word.",
    stem: "駅の前で友だちを待ちます。",
    focus: "待ちます",
    options: options("もちます", "たちます", "まちます", "ききます"),
    correctOptionId: "3",
    explanation:
      "待ちます is read まちます, “to wait.” もちます is 持ちます, “to hold.”",
    relatedKanji: ["駅", "前", "待"],
  },
  {
    id: "n5-orthography-yasumu",
    level: "N5",
    skill: "kanji",
    officialType: "orthography",
    shortQuiz: true,
    instruction: "Choose the best writing for the hiragana word.",
    stem: "あした、がっこうを やすみます。",
    focus: "やすみます",
    options: options("体みます", "休みます", "木みます", "本みます"),
    correctOptionId: "2",
    explanation:
      "The verb やすむ is written 休む. In polite form it is 休みます.",
    relatedKanji: ["休"],
  },
  {
    id: "n5-orthography-milk",
    level: "N5",
    skill: "kanji",
    officialType: "orthography",
    instruction: "Choose the best writing for the hiragana word.",
    stem: "スーパーで ぎゅうにゅうを 買いました。",
    focus: "ぎゅうにゅう",
    options: options("牛肉", "午乳", "牛乳", "午肉"),
    correctOptionId: "3",
    explanation: "ぎゅうにゅう (milk) is written 牛乳. 牛肉 means beef.",
    relatedKanji: ["牛", "乳", "買"],
  },
  {
    id: "n5-context-yasui",
    level: "N5",
    skill: "vocabulary",
    officialType: "context-expression",
    shortQuiz: true,
    instruction: "Choose the word that best completes the sentence.",
    stem: "このかばんは五百円です。とても＿＿です。",
    options: options("安い", "高い", "重い", "古い"),
    correctOptionId: "1",
    explanation:
      "At 500 yen, 安い (inexpensive) is the natural description. 高い means expensive.",
    relatedKanji: ["百", "円", "安", "高"],
  },
  {
    id: "n5-context-umbrella",
    level: "N5",
    skill: "vocabulary",
    officialType: "context-expression",
    instruction: "Choose the word that best completes the sentence.",
    stem: "雨がふっていますから、かさを＿＿。",
    options: options("きます", "はきます", "さします", "かぶります"),
    correctOptionId: "3",
    explanation:
      "The fixed expression is かさをさします, “to put up/use an umbrella.”",
    relatedKanji: ["雨"],
  },
  {
    id: "n5-paraphrase-company",
    level: "N5",
    skill: "vocabulary",
    officialType: "paraphrase",
    shortQuiz: true,
    instruction: "Choose the sentence with nearly the same meaning.",
    stem: "父は会社員です。",
    focus: "会社員",
    options: options(
      "父は会社で働いています。",
      "父は会社へ行きません。",
      "父は学校で勉強しています。",
      "父は家にいます。",
    ),
    correctOptionId: "1",
    explanation:
      "会社員 is a company employee, so the father works at a company.",
    relatedKanji: ["父", "会", "社", "員", "働"],
  },
  {
    id: "n5-paraphrase-bright",
    level: "N5",
    skill: "vocabulary",
    officialType: "paraphrase",
    instruction: "Choose the sentence with nearly the same meaning.",
    stem: "このへやは明るいです。",
    focus: "明るい",
    options: options(
      "このへやはしずかです。",
      "このへやはきれいではありません。",
      "このへやには光がたくさん入ります。",
      "このへやはとてもせまいです。",
    ),
    correctOptionId: "3",
    explanation:
      "明るい means bright; a room with a lot of light has the same meaning here.",
    relatedKanji: ["明", "光", "入"],
  },
  {
    id: "n5-grammar-sunday",
    level: "N5",
    skill: "grammar",
    officialType: "grammar-form",
    shortQuiz: true,
    instruction: "Choose the particle that best completes the sentence.",
    stem: "日曜日＿＿友だちと映画を見ました。",
    options: options("を", "に", "で", "へ"),
    correctOptionId: "2",
    explanation:
      "に marks the specific time when an action happened: 日曜日に見ました.",
    relatedKanji: ["日", "曜", "友", "映", "画", "見"],
  },
  {
    id: "n5-grammar-whose",
    level: "N5",
    skill: "grammar",
    officialType: "grammar-form",
    instruction: "Choose the particle that best completes the sentence.",
    stem: "これはだれ＿＿かさですか。",
    options: options("が", "を", "の", "と"),
    correctOptionId: "3",
    explanation: "だれの means “whose.” の links the owner to the object.",
  },
  {
    id: "n5-composition-school",
    level: "N5",
    skill: "grammar",
    officialType: "sentence-composition",
    instruction:
      "Put the four parts in the correct order. Which part goes in ★?",
    stem: "わたしは　＿＿　＿＿　★　＿＿　勉強します。",
    options: options("毎日", "学校", "で", "日本語を"),
    correctOptionId: "3",
    sentenceComposition: {
      canonicalOrderOptionIds: ["1", "2", "3", "4"],
      starredPosition: 2,
    },
    explanation:
      "The only natural order is 毎日 学校で 日本語を 勉強します, so で is in the starred third position.",
    relatedKanji: ["毎", "日", "学", "校", "日", "本", "語", "勉", "強"],
  },
  {
    id: "n5-text-grammar-holiday",
    level: "N5",
    skill: "grammar",
    officialType: "text-grammar",
    shortQuiz: true,
    instruction:
      "Read the passage and choose the expression that best fits the blank.",
    stem: "（　）に入るものとして、最もよいものを一つ選んでください。",
    passage: {
      body: "あしたは雨がたくさん降るそうです。動物園で昼ごはんを食べることはむずかしいです。＿＿、昼ごはんは学校の中で食べます。おべんとうをわすれないでください。",
    },
    options: options("でも", "ですから", "たとえば", "それから"),
    correctOptionId: "2",
    explanation:
      "ですから introduces the school's decision as the result of the forecast and the difficulty of eating at the zoo.",
    relatedKanji: ["雨", "動", "物", "園", "昼", "学", "校", "中", "食"],
  },
  {
    id: "n5-reading-note",
    level: "N5",
    skill: "reading",
    officialType: "reading-short",
    shortQuiz: true,
    instruction: "Read the note and choose the correct answer.",
    stem: "ゆきさんは何時に駅へ行きますか。",
    passage: {
      title: "メモ",
      body: "ゆきさんへ\nあした、いっしょに映画を見ましょう。映画は二時からです。一時半に駅の前で会いましょう。\nまり",
    },
    options: options("一時", "一時半", "二時", "二時半"),
    correctOptionId: "2",
    explanation:
      "The note says 一時半に駅の前で会いましょう, so Yuki should go at 1:30.",
    relatedKanji: ["映", "画", "時", "駅", "前", "会"],
  },
  {
    id: "n5-reading-lunch",
    level: "N5",
    skill: "reading",
    officialType: "reading-mid",
    instruction: "Read the passage and choose the correct answer.",
    stem: "田中さんは、どうしてパンを買いませんでしたか。",
    passage: {
      body: "田中さんは昼ごはんを買いに店へ行きました。パンを買いたかったですが、店にはパンがありませんでした。それで、おにぎりを二つ買いました。店を出たあとで、水を買うのをわすれたことに気がつきました。",
    },
    options: options(
      "パンが高かったから",
      "パンが好きではないから",
      "店にパンがなかったから",
      "おにぎりを家から持ってきたから",
    ),
    correctOptionId: "3",
    explanation: "The passage directly states 店にはパンがありませんでした.",
    relatedKanji: ["田", "中", "昼", "買", "店", "二", "水", "気"],
  },
  {
    id: "n5-reading-library",
    level: "N5",
    skill: "reading",
    officialType: "information-retrieval",
    instruction: "Use the notice to find the needed information.",
    stem: "木曜日の午後六時に本を返すことができますか。",
    passage: {
      title: "さくら図書館",
      body: "月・火・木・金　午前九時〜午後七時\n土・日　午前十時〜午後五時\n水曜日　休み\n本を返すだけの人は、入口の右の箱に入れてください。図書館が休みのときも使えます。",
    },
    options: options(
      "はい、図書館の中で返せます。",
      "はい、入口の箱だけ使えます。",
      "いいえ、木曜日は休みです。",
      "いいえ、午後五時に閉まります。",
    ),
    correctOptionId: "1",
    explanation:
      "On Thursday the library is open until 7 p.m., so at 6 p.m. the book can be returned inside.",
    relatedKanji: [
      "木",
      "曜",
      "午",
      "後",
      "六",
      "時",
      "本",
      "返",
      "図",
      "書",
      "館",
    ],
  },
  {
    id: "n5-listening-cafe",
    level: "N5",
    skill: "listening",
    officialType: "listening-task",
    shortQuiz: true,
    instruction: "Listen and choose what the man will buy.",
    stem: "男の人は何を買いますか。",
    listening: {
      script:
        "女の人：飲み物は何にしますか。\n男の人：コーヒーはきのう飲みました。きょうは暑いですね。冷たいお茶をください。",
      maxPlays: 2,
      rate: 0.82,
    },
    options: options(
      "温かいコーヒー",
      "冷たいコーヒー",
      "温かいお茶",
      "冷たいお茶",
    ),
    correctOptionId: "4",
    explanation: "The man says 冷たいお茶をください, so he will buy cold tea.",
    relatedKanji: ["男", "女", "飲", "暑", "冷", "茶"],
  },
  {
    id: "n5-listening-class",
    level: "N5",
    skill: "listening",
    officialType: "listening-key-points",
    shortQuiz: true,
    instruction: "Read the question, listen, and choose the correct answer.",
    stem: "日本語のクラスは何曜日ですか。",
    listening: {
      script:
        "男の人：日本語のクラスは火曜日ですか。\n女の人：いいえ、前は火曜日でしたが、今月から木曜日です。",
      maxPlays: 2,
      rate: 0.82,
    },
    options: options("月曜日", "火曜日", "水曜日", "木曜日"),
    correctOptionId: "4",
    explanation:
      "It used to be Tuesday, but 今月から木曜日です means it is Thursday from this month.",
    relatedKanji: ["日", "本", "語", "火", "曜", "前", "今", "月", "木"],
  },
  {
    id: "n5-listening-verbal",
    level: "N5",
    skill: "listening",
    officialType: "listening-verbal",
    instruction:
      "Look at the illustration, listen to the situation and three expressions, and choose the best one.",
    stem: "店でほしいシャツを店員に見せてもらいます。何と言いますか。",
    listening: {
      script:
        "服の店で、女の人がシャツを見ています。店員にシャツを見せてもらいたいです。何と言いますか。\n一、あのシャツを見せてください。\n二、このシャツを見ませんか。\n三、シャツを見ていました。",
      audioOnlyOptions: true,
      verbalScene: {
        setting: "shop",
        speaker: { side: "left", pose: "pointing" },
        partner: { side: "right", pose: "neutral" },
        prop: { kind: "shirt", position: "center" },
        description:
          "A customer points to a shirt on display while a shop clerk stands nearby.",
      },
      maxPlays: 2,
      rate: 0.8,
    },
    options: options(
      "あのシャツを見せてください。",
      "このシャツを見ませんか。",
      "シャツを見ていました。",
    ),
    correctOptionId: "1",
    explanation:
      "あのシャツを見せてください is the appropriate request to a shop employee.",
    relatedKanji: ["店", "員", "見"],
  },
  {
    id: "n5-listening-quick-book",
    level: "N5",
    skill: "listening",
    officialType: "listening-quick-response",
    shortQuiz: true,
    instruction: "Listen and choose the best response.",
    stem: "いちばんいい答えを選んでください。",
    listening: {
      script:
        "これはだれの本ですか。\n一、田中さんのです。\n二、図書館へ行きます。\n三、三冊あります。",
      audioOnlyOptions: true,
      maxPlays: 2,
      rate: 0.82,
    },
    options: options("1", "2", "3"),
    correctOptionId: "1",
    explanation:
      "The question asks whose book it is. 田中さんのです directly answers ownership.",
    relatedKanji: ["本", "田", "中", "図", "書", "館", "三", "冊"],
  },
  {
    id: "n5-listening-bus",
    level: "N5",
    skill: "listening",
    officialType: "listening-task",
    instruction: "Listen and choose what the woman will do next.",
    stem: "女の人はこのあと、まず何をしますか。",
    listening: {
      script:
        "女の人：すみません、駅へ行くバスはどこですか。\n男の人：この道をまっすぐ行って、二つ目の角を右に曲がってください。バス停はコンビニの前です。\n女の人：わかりました。",
      maxPlays: 2,
      rate: 0.82,
    },
    options: options(
      "一つ目の角を右に曲がる",
      "二つ目の角を右に曲がる",
      "コンビニで買い物をする",
      "駅まで歩く",
    ),
    correctOptionId: "2",
    explanation: "The directions say 二つ目の角を右に曲がってください.",
    relatedKanji: ["女", "男", "駅", "道", "二", "目", "角", "右", "曲", "前"],
  },
];

export const N5_QUESTIONS: readonly JlptQuestion[] = [
  ...N5_AUTHORED_QUESTIONS.filter(
    (question) => question.officialType !== "listening-verbal",
  ),
  ...N5_GENERATED_QUESTIONS,
];
